### ISSUE TITLE
Adding custom fields to user in FaunaDB adapter

### ISSUE THREAD

**Issue by dsbrianwebster** [nextauthjs/adapters#100]
Question around best practices...

For the fauna DB adapter, let's say we had a bunch of other profile information on the user, would you recommend forking the adapter and adjusting the create and update user functions to suit project requirements? Or would you recommend another collection in fauna like 'profiles' that has a ref to the user collection?

**Comment by ndom91** [comment]
Hi `dsbrianwebster`, thanks for the question!

Currently I'd recommend another collection that refs the next-auth user collection. 

However, someone recently added a PR to support custom fields in the User colleciton in the `typeorm` adapter. We're currently working on getting it merged and would like to extend that functionality to all adapters then :+1:

**Comment by pbteja1998** [comment]
Yes, I also think this would be very cool. I had a similar usecase so many times. One workaround that I have been using in my projects is to add everything I receive from `profile` callback to the user object — instead of only taking the relevant fields and adding them.

**Comment by pbteja1998** [comment]
Although, I think this would make it harder to type the functions, if we do like I said(adding everything we receive in profile callback to user)

**Comment by ndom91** [comment]
As there is current no way to do this, I am going to close this issue for the time being.

There is discussion in #43 about adding the ability to import custom models, however. So that seems like the most appropriate place to continue that discussion.

Feel free to reopen if need be.
