### ISSUE TITLE
How to use roles and permissions with fauna adapter

### ISSUE THREAD

**Issue by dsbrianwebster** [nextauthjs/adapters#103]
It's unclear how (or if) one can use NextAuth with fauna and still leverage their awesome built in ABAC roles and permissions. Is it possible to access the fauna token from the session to pass into faunaClient so we may query the dB a specific user?

**Comment by pbteja1998** [comment]
@dsbrianwebster yes, you are right. It's currently not possible. But I would say it's in the works. Check the below comment.

https://github.com/nextauthjs/adapters/pull/43#issuecomment-831172767

**Comment by dsbrianwebster** [comment]
@pbteja1998 thank you! You're the man. I keep bumping into you on git, from your starter to these adapters. We're both clearly fans of a very similar stack 🚀

**Comment by ndom91** [comment]
Hey guys I'm going to close this issue for now. Further discussion on how to accomplish this technically can be done in the PR (#43) or feel free to reopen this or create a new issue if need be :+1:
