### ISSUE TITLE
Incompatible types in NextAuth config

### ISSUE THREAD

**Issue by btmorex** [nextauthjs/adapters#107]
Using the prisma instructions from the website, I'm getting the following error:

```
./src/pages/api/auth/[...nextauth].ts:18:3
Type error: Type '{ getAdapter: (appOptions?: any) => Promise<{ createUser: (profile: any) => Promise<User>; getUser: (id: number) => Promise<User | null>; getUserByEmail: (email?: string | undefined) => Promise<...>; ... 11 more ...; deleteVerificationRequest: (identifier: string, token: string, secret: string, provider: string) => ...' is not assignable to type '{ getAdapter(appOptions: AppOptions): Promise<AdapterInstance<unknown, unknown, unknown>>; }'.
  The types returned by 'getAdapter(...)' are incompatible between these types.
    Type 'Promise<{ createUser: (profile: any) => Promise<User>; getUser: (id: number) => Promise<User | null>; getUserByEmail: (email?: string | undefined) => Promise<User | null>; ... 11 more ...; deleteVerificationRequest: (identifier: string, token: string, secret: string, provider: string) => Promise<...>; }>' is not assignable to type 'Promise<AdapterInstance<unknown, unknown, unknown>>'.
      Type '{ createUser: (profile: any) => Promise<User>; getUser: (id: number) => Promise<User | null>; getUserByEmail: (email?: string | undefined) => Promise<User | null>; ... 11 more ...; deleteVerificationRequest: (identifier: string, token: string, secret: string, provider: string) => Promise<...>; }' is not assignable to type 'AdapterInstance<unknown, unknown, unknown>'.
        Types of property 'getUser' are incompatible.
          Type '(id: number) => Promise<User | null>' is not assignable to type '(id: string) => Promise<unknown>'.
            Types of parameters 'id' and 'id' are incompatible.
              Type 'string' is not assignable to type 'number'.

  16 | 
  17 | export default NextAuth({
> 18 |   adapter: PrismaAdapter({prisma}),
     |   ^
  19 |   providers: [
  20 |     Providers.Email({
  21 |       server: {
```

**Comment by QuiiBz** [comment]
Same issue here. Also, I had to import PrismaAdapter by default:
```
import PrismaAdapter from "@next-auth/prisma-adapter"
```

But the documentation says to import it like so:
```
import { PrismaAdapter } from "@next-auth/prisma-adapter"
```

This is not possible since it only exports a default function.

**Comment by balazsorban44** [comment]
It depends on which adapters you are trying to use.

@QuiiBz looks like you are using this one: https://github.com/nextauthjs/adapters/blob/canary/packages/prisma/src/index.ts which does not have a default import!

@btmorex I still have to verify your case.

The new https://github.com/nextauthjs/adapters/blob/canary/packages/prisma/prisma/schema.prisma
and the old: https://github.com/nextauthjs/adapters/blob/canary/packages/prisma-legacy/prisma/schema.prisma

adapters have different schemas. I think there is an error in our release process, which might have produced the wrong TS definition types for the legacy adapter.

**Comment by btmorex** [comment]
I think the problem is that the website is documenting an unreleased version. I installed 0.4.4-canary.57 and everything works the way the website suggests, but that's not the version you get when running `yarn add @next-auth/prisma-adapter`.

**Comment by balazsorban44** [comment]
:confused: Trying to land on a stable release for the adapter, versioning is a bit messy at the moment, sorry for that! So this is actually a non-issue then?

**Comment by btmorex** [comment]
I think it's a doc issue. At least it would be nice if the web site docs corresponded to the released version.

**Comment by balazsorban44** [comment]
OK, will keep this open then, until we clean it up!

**Comment by ndom91** [comment]
Docs have been updated and are pointing to the latest `canary` releases now. Closing this :+1:
