### ISSUE TITLE
Correctly set up release flow

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/adapters#109]
I am not an expert on setting up monorepos, so this is a call to anyone who have some knowledge in this area!

- I would like if PRs only run tests/builds/publishing for packages that have been touched in that PR.
- It would be nice if each push to the PR gets published so it can be tested before merging.
- I would like to generate CHANGELOGs automatically, by controlling the commit messages when a PR is merged to a release branch (with squash and merge). The CHANGELOGs should preferably be available in the releases tab https://github.com/nextauthjs/adapters/releases
- Merging to a release branch should only run tests/builds/publish for changed packages.

Currently we use [Lerna](https://github.com/lerna/lerna), but I am open to alternatives. It fails from time to time, all tests are always run on each PR, even if the PR did not touch a package, which results in sub-optimal GitHub Action run times. I just want the process to be as automatic as possible. 🙏 If you think you can help or has an idea, please share!

**Comment by bhushan-shah-dev** [comment]
I have some experience with monorepos. I could help out a bit, though can't guarantee I would be able to fix all the problems listed above.

Where can I start?

**Comment by balazsorban44** [comment]
Thank you for chipping in @bhushan-shah-dev!

So we have our worflow configurations here:
https://github.com/nextauthjs/adapters/blob/canary/.github/workflows/canary.yml
and here: https://github.com/nextauthjs/adapters/blob/canary/.github/workflows/main.yml

They both use lerna, but currently they run all the tests for each package on each PR, and all the builds for ALL packages afterwards, even if they did not change.

For starters, it would be nice to get this figured out. Only run relevant tests and builds on PR.

**Comment by MichaelDeBoey** [comment]
@JamesHenry is switching from @lerna to [NX](https://github.com/nrwl/nx) in the @typescript-eslint repo, so probably a good idea to look at that one too

Ref: https://github.com/typescript-eslint/typescript-eslint/pull/3465

**Comment by JamesHenry** [comment]
Not switching, no. Adding Nx to do what it’s good at, and leaving lerna to do what it’s good at. Nx works great in addition to lerna.

**Comment by JamesHenry** [comment]
You can learn more from this blog post and the video within it: https://blog.nrwl.io/adding-nx-to-an-existing-monorepo-by-running-one-command-426fa519d943

**Comment by ndom91** [comment]
So after doing some basic research, it seems that nx is great at the test only the changed portions, cache everything intelligently (and across different computers with nx cloud), etc. I'm going to look a bit further into it if it can help us with the release process as well and maybe whip up a test PR :+1:
