### ISSUE TITLE
Invalid `prisma.account.findUnique()` invocation -  Provided Int, expected String

### ISSUE THREAD

**Issue by tom-richter** [nextauthjs/adapters#111]
Hi, I first had a `TypeError: Cannot read property 'findUnique' of undefined`. I fixed it by using `adapter: PrismaAdapter(prisma)` instead of `adapter: PrismaAdapter({prisma})`. Now I'm getting this error: 

```
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'github',
      providerAccountId: 12345678
                         ~~~~~~~~
    }
  },
  select: {
    user: true
  }
}
Argument providerAccountId: Got invalid value 12345678 on prisma.findUniqueAccount. Provided Int, expected String.
```
I could change providerAccountId in the Account model from String to Int. Converting the providerAccountId into a string also works:

```
const account = await prisma.account.findUnique({
    where: {
        providerId_providerAccountId: { providerId, providerAccountId: providerAccountId.toString() },
    },
    select: { user: true },
});
```
I guess providerAccountId should be a string so why is `getUserByProviderAccountId(providerId, providerAccountId)` called with an integer providerAccountId?

Same issue with:
prisma.createOneAccount

**Comment by tom-richter** [comment]
Nevermind, I just followed the canary docs and got it working: https://next-auth-git-canary-nextauthjs.vercel.app/schemas/adapters#prisma-adapter

**Comment by TimPietrusky** [comment]
@tom-richter I have the exact same problem, but I can't get it working, even when my code is exactly what the canary docs look like and I also have the latest versions (tried both "latest" and "canary"). Still the error with

```
Invalid `prisma.user.findUnique()` invocation:

{
  where: {
    id: '1'
        ~~~
  }
}

Argument id: Got invalid value '1' on prisma.findUniqueUser. Provided String, expected Int.
```

**Comment by TimPietrusky** [comment]
The problems only came when I updated from next-auth@3.14.0 to the latest version. So I downgraded it again.

**Comment by tom-richter** [comment]
As mentioned in #116 the canary docs are outdated and @next-auth/prisma-adapter will be used in the future. 

Using these package versions, the issue still exists:

```
"@next-auth/prisma-adapter": "^0.4.4-canary.64",
"@prisma/client": "^2.23.0",
"next-auth": "^3.23.3",
```

**Comment by tom-richter** [comment]
I think the problem is that in #72 some model fields were changed from Int to String, but some parts of the code still use integers.

If the arguments of 

`async getUserByProviderAccountId(providerId, providerAccountId) {...}`

would have been typed properly, this regression could have been prevented by TypeScript.

**Comment by balazsorban44** [comment]
If the GitHub id is the problem here, I think it should be converted in this file: https://github.com/nextauthjs/next-auth/blob/main/src/providers/github.js

**Comment by tom-richter** [comment]
How can I override the provider config? I can't find any documentation for this.

**Comment by tom-richter** [comment]
Thank you, overriding the provider config works for me:

```js
import NextAuth, { User as NextAuthUser } from 'next-auth'
interface NextAuthUserWithStringId extends NextAuthUser {
  id: string
}
...
Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
      profile(profile) {
        return {
          id: profile.id.toString(),
          name: profile.name || profile.login,
          email: profile.email,
          image: profile.avatar_url,
        } as NextAuthUserWithStringId
      },
    }),
...
```

**Comment by ndom91** [comment]
Thanks for working through this @tom-richter and opening a PR!

As @balazsorban44 mentioned in the PR, this would be a breaking change for people who have already worked around it and are expecting it to be an integer, so we will hold off until the next major version to merge that breaking change.

Until then I will close this issue, any further discussion about the fix can happen in that PR. Feel free to reopen this or create a new issue if need be.
