### ISSUE TITLE
neo4j adapter.

### ISSUE THREAD

**Issue by EarthlingDavey** [nextauthjs/adapters#113]
Hi, has anyone worked on this so far?

I want to try and do it over the next few days.

I'll try and write it in TypeScript although I usually write JavaScript.

If I need some guidance with TS, is a maintainer available to chat? 

For that or any other suggestions, I'm in [Next.js - Discord](https://discord.com/invite/w8p9Psrk2M).

**Comment by balazsorban44** [comment]
If you open a PR, we'll be here to help :) We can keep communication in the PR itself, so it is easy to track the progress.

**Comment by EarthlingDavey** [comment]
Hi @balazsorban44 I've made a PR.

**Comment by ndom91** [comment]
Will close this issue so we can continue discussion in the PR!
