### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED] - Prisma

### ISSUE THREAD

**Issue by nickgravel** [nextauthjs/adapters#115]
I am trying to setup NextAuth with Prisma adapter.
I am getting the following error:

>Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/errors' is not defined by "exports" in /[...]/node_modules/next-auth/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:437:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.mod._resolveFilename (/[...]/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/[...]/node_modules/@next-auth/prisma-adapter/dist/index.js:54:16) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

I am using node v14.17.0

"@next-auth/prisma-adapter": "^0.4.4",
"@prisma/client": "^2.23.0",
"next": "^10.2.0",
"next-auth": "^3.24.0",

Any insight on this issue would be greatly appreciated.

**Comment by amcclosky** [comment]
I am hitting this same issue at the moment.

**Comment by balazsorban44** [comment]
Please search through issues before posting.

https://github.com/nextauthjs/adapters/issues/105

**Comment by nickgravel** [comment]
The error is still occurring after upgrading to "@next-auth/prisma-adapter": "^0.4.4-canary.64"
Same console output.

The error displayed on my screen is different than posted in  #105 :
![Screen Shot 2021-05-28 at 8 48 03 PM](https://user-images.githubusercontent.com/918742/120053319-8db1d000-bff7-11eb-8c96-4fdf55cd4721.png)

**Comment by nickgravel** [comment]
I added the following keys to next-auth/package.json

> "exports": {
    ".": "./dist/server/index.js",
    "./jwt": "./dist/lib/jwt.js",
    "./adapters": "./dist/adapters/index.js",
    "./client": "./dist/client/index.js",
    "./providers": "./dist/providers/index.js",
    "./providers/*": "./dist/providers/*.js",
    "./errors": "./dist/lib/errors.js",
    **"./dist/lib/errors": "./dist/lib/errors.js",
    "./dist/lib/logger": "./dist/lib/logger.js"**
  },

And now my errors are no longer displayed...

**Comment by balazsorban44** [comment]
you did not update correctly then. the newest version of the Prisma adapter does not require those exports. do you maybe have a reproduction repository?

**Comment by qedr** [comment]
I'm had the exact same issue as @nickgravel and adding those two lines has stopped the errors...

**Comment by balazsorban44** [comment]
could some of you who have this issue create a reproduction? I'm not able to reproduce it with the suggested changes.

**Comment by nickgravel** [comment]
Sure, here's a reproduction:
https://github.com/nickgravel/next-auth-prisma-err

**Comment by balazsorban44** [comment]
Looking at your lock file, I see it still uses the wrong version. Make sure it's updated correctly.

**Comment by nickgravel** [comment]
Alright thanks.

I had to explicitly install the canary version via npm:

`npm install @next-auth/prisma-adapter@0.4.4-canary.64`

Once I did that, I longer experienced the errors mentioned in my issue.
I had to run that command even though my package.json file had `"@next-auth/prisma-adapter": "^0.4.4-canary.64",` dependency already stated; didn't matter whether or not it was a new install.

Have to do:
`npm i`, then
`npm install @next-auth/prisma-adapter@0.4.4-canary.64`

**Comment by qedr** [comment]
Have just attempted explicitly installing the canary version via npm.
I now get a different error when using the email provider - after clicking "sign in with email", I get this error:

```
[next-auth][error][prisma__get_session_error] 
https://next-auth.js.org/errors#prisma__get_session_error TypeError: Cannot read property 'findUnique' of undefined
    at getSession (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:96:58)
    at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
    at Object.session (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/session.js:80:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[next-auth][error][session_error] 
https://next-auth.js.org/errors#session_error TypeError: Cannot read property 'findUnique' of undefined
    at getSession (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:96:58)
    at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
    at Object.session (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/session.js:80:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  name: 'GetSessionError'
}
[next-auth][error][prisma__get_user_by_email_error] 
https://next-auth.js.org/errors#prisma__get_user_by_email_error TypeError: Cannot read property 'findUnique' of undefined
    at getUserByEmail (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:36:40)
    at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
    at Object.signin (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/signin.js:50:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError: Cannot read property 'findUnique' of undefined
    at getUserByEmail (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:36:40)
    at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
    at Object.signin (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/signin.js:50:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  name: 'GetUserByEmailError'
}
```

**Comment by nickgravel** [comment]
> Have just attempted explicitly installing the canary version via npm.
> I now get a different error when using the email auth provider - after clicking "sign in with email", I get this error:
> 
> (I wasn't having this issue when I did the 2 line fix mentioned above)
> 
> ```
> [next-auth][error][prisma__get_session_error] 
> https://next-auth.js.org/errors#prisma__get_session_error TypeError: Cannot read property 'findUnique' of undefined
>     at getSession (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:96:58)
>     at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
>     at Object.session (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/session.js:80:29)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> [next-auth][error][session_error] 
> https://next-auth.js.org/errors#session_error TypeError: Cannot read property 'findUnique' of undefined
>     at getSession (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:96:58)
>     at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
>     at Object.session (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/session.js:80:29)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
>   name: 'GetSessionError'
> }
> [next-auth][error][prisma__get_user_by_email_error] 
> https://next-auth.js.org/errors#prisma__get_user_by_email_error TypeError: Cannot read property 'findUnique' of undefined
>     at getUserByEmail (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:36:40)
>     at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
>     at Object.signin (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/signin.js:50:28)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> node:internal/process/promises:245
>           triggerUncaughtException(err, true /* fromPromise */);
>           ^
> 
> TypeError: Cannot read property 'findUnique' of undefined
>     at getUserByEmail (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:36:40)
>     at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
>     at Object.signin (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/signin.js:50:28)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
>   name: 'GetUserByEmailError'
> }
> ```

In [...nextauth].js, try updating 
`adapter: PrismaAdapter({ prisma }),`

to
`adapter: PrismaAdapter(prisma),`

**Comment by qedr** [comment]
> > Have just attempted explicitly installing the canary version via npm.
> > I now get a different error when using the email auth provider - after clicking "sign in with email", I get this error:
> > (I wasn't having this issue when I did the 2 line fix mentioned above)
> > ```
> > [next-auth][error][prisma__get_session_error] 
> > https://next-auth.js.org/errors#prisma__get_session_error TypeError: Cannot read property 'findUnique' of undefined
> >     at getSession (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:96:58)
> >     at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
> >     at Object.session (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/session.js:80:29)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> > [next-auth][error][session_error] 
> > https://next-auth.js.org/errors#session_error TypeError: Cannot read property 'findUnique' of undefined
> >     at getSession (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:96:58)
> >     at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
> >     at Object.session (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/session.js:80:29)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
> >   name: 'GetSessionError'
> > }
> > [next-auth][error][prisma__get_user_by_email_error] 
> > https://next-auth.js.org/errors#prisma__get_user_by_email_error TypeError: Cannot read property 'findUnique' of undefined
> >     at getUserByEmail (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:36:40)
> >     at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
> >     at Object.signin (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/signin.js:50:28)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> > node:internal/process/promises:245
> >           triggerUncaughtException(err, true /* fromPromise */);
> >           ^
> > 
> > TypeError: Cannot read property 'findUnique' of undefined
> >     at getUserByEmail (/Users/xyz/Code/Projects/hirevine/node_modules/@next-auth/prisma-adapter/dist/index.js:36:40)
> >     at acc.<computed> (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/adapters/error-handler.js:19:22)
> >     at Object.signin (/Users/xyz/Code/Projects/hirevine/node_modules/next-auth/dist/server/routes/signin.js:50:28)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
> >   name: 'GetUserByEmailError'
> > }
> > ```
> 
> In [...nextauth].js, try updating
> `adapter: PrismaAdapter({ prisma }),`
> 
> to
> `adapter: PrismaAdapter(prisma),`

Thank you! This fixed it for me :)

**Comment by balazsorban44** [comment]
cc @ndom91 the wrong API docs I mentioned in the other issue.

**Comment by ndom91** [comment]
@balazsorban44 updated the docs and the adapters readme to clarify this `prisma`/`prisma-legacy` situation.
