### ISSUE TITLE
Unknown arg `providerId_providerAccountId`

### ISSUE THREAD

**Issue by thecodelearner** [nextauthjs/adapters#121]
> @thecodelearner see #105 #115 #118

apologies if this is redundant again, although I've gone through the three linked issues, and seems it's a different problem now:

```
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error Error: 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      providerId: 'google',
      providerAccountId: '********876014'
    }
  },
  select: {
    user: true
  }
}

Unknown arg `providerId_providerAccountId` in where.providerId_providerAccountId for type AccountWhereUniqueInput. Available args:

type AccountWhereUniqueInput {
  id?: String
  Account.providerId_providerAccountId_unique?: AccountAccount.providerId_providerAccountId_uniqueCompoundUniqueInput
}


    at Document.validate (/Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:32776:19)
    at NewPrismaClient._executeRequest (/Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:34718:17)
    at /Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:34653:52
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at NewPrismaClient._request (/Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:34653:25)
    at Object.then (/Users/sahil/code/carbon-ghost/node_modules/@prisma/client/runtime/index.js:34773:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  name: 'GetUserByProviderAccountIdError'
```

I did try this as well: https://github.com/nextauthjs/adapters/issues/115#issuecomment-850926328

_Originally posted by @thecodelearner in https://github.com/nextauthjs/adapters/issues/120#issuecomment-851421462_

**Comment by thecodelearner** [comment]
fixed this issue by updating `schema.prisma` as mentioned in the canary docs here: https://next-auth-git-canary-nextauthjs.vercel.app/schemas/adapters

**Comment by balazsorban44** [comment]
Superb! Glad it worked out. We are constantly working on getting the docs/schemas/adapters up-to-date, apologies for any hiccups along the way. We will get there :slightly_smiling_face:

**Comment by ml170722d** [comment]
> fixed this issue by updating `schema.prisma` as mentioned in the canary docs here: https://next-auth-git-canary-nextauthjs.vercel.app/schemas/adapters

I'm having the same issue mention above. I've read multiple issues on this topic and I have seen this canary link few times but it look like it's down. I'm getting '404 Page not found'. Could someone please check what is going on with that page or perhaps provide working link?  Thanks in advance😄
