### ISSUE TITLE
Firebase Adapter Error Module not found: Can't resolve '@next-auth/firebase-adapter'

### ISSUE THREAD

**Issue by boobewc** [nextauthjs/adapters#122]
![image](https://user-images.githubusercontent.com/9090968/120302631-4cbc0300-c2f8-11eb-85a9-6277b70e4ffd.png)

https://next-auth.js.org/adapters/firebase#options
I'm Following These Step and got Error Message Like This.
Please Help.

**Comment by balazsorban44** [comment]
please use the search before opening an issue

https://github.com/nextauthjs/adapters/issues/99
