### ISSUE TITLE
DynamoDB Adaptor documentation should be adjusted

### ISSUE THREAD

**Issue by manishprivet** [nextauthjs/adapters#125]
Hi, so I wanted to try next-auth in a serverless vercel app, and we were using DynamoDB, so followed the setup instructions from here https://next-auth.js.org/adapters/dynamodb, but somehow the adaptor was not working. So I decided to inspect the code and found out that the code was completely broken, with wrong sdk calls, and wrong instructions in the documentation itself.

I'll explain it one by one.

# 1. Wrong documentation

In the docs, we're supposed to use the docs like this
```js
adapter: DynamoDBAdapter({
    AWS,
    tableName: "next-auth-test",
  }),
```

But, if we look at the adaptor code
https://github.com/nextauthjs/adapters/blob/4177a25996560287f9a4f08a92ca1c44d7eaf36e/packages/dynamodb/src/index.ts#L5-L13
It's supposed to have two parameters, one for the DynamoDB client, and the other with an object containing the `tableName`.

So, the current documentation should be

```js
adapter: DynamoDBAdapter(
  new AWS.DynamoDB(),
  { tableName: "next-auth-test" })
```

# 2. Wrong use of AWS SDK and DynamoDB Client
Some of the functions in `aws-sdk` DynamoDB client for CRUD operations are:

1. `putItem`
2. `getItem`
3. `updateItem`

While the ones used here is

1. `get`
2. `put`
3. `update`

which simply throws an error like `client.put is not a function`.

# 3. Wrong query syntax

Let's take this example
https://github.com/nextauthjs/adapters/blob/4177a25996560287f9a4f08a92ca1c44d7eaf36e/packages/dynamodb/src/index.ts#L33-L45
This is fine for next-auth as it expects its response in this format only.

But the correct query for DynamoDB should contain

```js
const item: any = {
  pk: {S: `USER#${userId}`},
  sk: {S: `USER#${userId}`},
  id: {S: userId},
  type: {S: "USER"},
  name: {S: profile.name || ""},
  email: {S: profile.email || ""},
  image: {S: profile.image || ""},
  username: {S: profile.username || ""},
  emailVerified:  {S: profile.emailVerified?.toISOString() ?? ""},
  createdAt: {S: now.toISOString()},
  updatedAt: {S: now.toISOString()},
 }
```
So any entity object needs to be parsed between for next-auth and DynamoDB format, in all functions.

Or it'll simply throw an infinite number of validation errors.

As of now, since I really like the concept of next-auth, I'm rebuilding the dynamodb adaptor with all the corrections and by using [TypeDORM](https://github.com/typedorm/typedorm), which is a well strongly typed ORM for DynamoDB.

I'll soon create a PR for that, but up to that time, I think this should be taken down from the official docs of next-auth.

**Comment by okeeffed** [comment]
Ha! How coincidental, I just went to the docs to try this out and noticed how broken it was 😂

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/adapters/pull/44 introduced this adapter.

@PolMrt care to comment? Unfortunately I have no experience with DynamoDB, but open for suggestions on how to fix it.

**Comment by PolMrt** [comment]
Hi, [ this version of the adapter](https://github.com/PolMrt/adapters/blob/a986e20bb0900a9850b6df4424f2e2cc7474e8b9/packages/dynamodb/index.js) was working fine but it seems that bug have been introduced in the commit 44085f873d65fc55c73df5e7a0e751af26f70b06 were my version was rewrited (old: packages/dynamodb/index.js, new: packages/dynamodb/src/index.ts in the commit) in order to bring ts support and other new requirement for adapters (I guess).

In my version of the adapter, it required that you pass the entire AWS sdk to it, then it uses the `AWS.DynamoDB.DocumentClient()` which accept method such as get, put, update, delete and all requests were working smoothly. 

Maybe try : 

```javascript
adapter: DynamoDBAdapter(
  new AWS.DynamoDB.DocumentClient(),
  { tableName: "next-auth-test" })
```

I cannot guarantee this will work, but hopefully it will.
I'm sorry, but I currently don't have the time to fix this, but I'll be happy to fix that when I've got the time to.

**Comment by manishprivet** [comment]
@PolMrt It works fine now, thanks. I thought that `new AWS.DynamoDB()` was supposed to be used here. Really grateful for the quick reply as I was thinking to write my own adapter 😅 

@balazsorban44 Apologies for the issue on the main repo and this issue can also be closed now. I think the documentation still needs to be updated though.

**Comment by balazsorban44** [comment]
Very happy that this worked out so fast! I am happy to accept PRs to clarify the documentation!

**Comment by ndom91** [comment]
#126 was merged today. This seems to address the documentation issues which were brought to light in this issue. Can we close this or is there still something else open?
