### ISSUE TITLE
hasura Adapter

### ISSUE THREAD

**Issue by kedarguy** [nextauthjs/adapters#128]
Is there a Hasura adaptor in progress? 

I found this [project ](https://github.com/sondh0127/nextjs-hasura-fullstack)that uses Hasura with the Prisma adaptor, is that advisable?

**Comment by ndom91** [comment]
So there is not a hasura adapter available from us. The project you linked actually seems to use the prisma adapter for next-auth.

I found a separate blog post from hasura, however, about how to use next-auth with hasura which does not use any db backend/provider, but uses next-auth via a custom hasura jwt "claim". https://hasura.io/blog/next-js-jwt-authentication-with-next-auth-and-integration-with-hasura/.

**Comment by ndom91** [comment]
Closing this for now. If you have any other questions or need help feel free to reopen if its related or open another issue :+1:
