### ISSUE TITLE
Custom fields with prisma adapter

### ISSUE THREAD

**Issue by sachinraja** [nextauthjs/adapters#131]
I want to save the username of the user's profile on the GitHub OAuth, but saving custom fields for prisma does not seem to be documented anywhere. I have tried to do this:
```ts
export default NextAuth({
  providers: [
    Providers.GitHub({
      clientId: envConfig.get('gitHub.clientId'),
      clientSecret: envConfig.get('gitHub.clientSecret'),
      profile(profile) {
        return {
          // @ts-expect-error id does exist
          id: profile.id.toString(),
          // USERNAME DEFINED HERE
          username: profile.login,
          bio: profile.bio,
          name: profile.name ?? profile.login,
          email: profile.email,
          image: profile.avatar_url,
        } as UserWithStringId
      },
    }),
  ],
  adapter: PrismaAdapter(prisma),
  session: { jwt: true },
})
```
but `username` is not added to `data` when `prisma.user.create` is called and the function errors. Is there any way to do this?

**Comment by balazsorban44** [comment]
Not really sure why we don't pass the whole profile here:

https://github.com/nextauthjs/adapters/blob/4961e43c72d2dfe21ff43726f066b7240dedfb56/packages/prisma/src/index.ts#L28-L34

Looking at the original adapter here: https://github.com/nextauthjs/adapters/blob/4961e43c72d2dfe21ff43726f066b7240dedfb56/packages/typeorm-legacy/src/index.js#L124-L126 looks like it passes the entire profile object, so it shouldn't be a problem to do the same for Prisma either. Not sure about how it affects schemas and such. @ndom91?

**Comment by ndom91** [comment]
Hey so I'm not positive what affect it would have schema wise - only thing I can think of is it'll overwrite your custom field if you tear the db down and recreate it with prisma. 

I whipped up a quick PR and all tests pass. I pinged williamluke4 in the PR since he seems to knwo the most about prisma.
