### ISSUE TITLE
TypeORMLegacyAdapter: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by denkristoffer** [nextauthjs/adapters#154]
:wave:

The TypeORM adapter doesn't currently work with MySQL 8, it throws with the following error: "Client does not support authentication protocol requested by server; consider upgrading MySQL client".

TypeORM uses the `mysql` package when it's available, and unfortunately this doesn't support the default authentication method of MySQL 8. The alternative package `mysql2` works with MySQL 8, and TypeORM can use that package as well, but when both packages are installed it defaults to `mysql` [because of this switch](https://github.com/typeorm/typeorm/blob/beea2e1e4429d13d7864ebc23aa6e58fa01647ea/src/platform/PlatformTools.ts). The TypeORM adapter currently installs `mysql` as a dependency which is why things are breaking even if the user has manually installed `mysql2`.

https://github.com/typeorm/typeorm/issues/2093#issuecomment-706692887 for reference.

**Comment by ndom91** [comment]
Strange, we run our typeorm mysql tests with the `mysql:8` container and they've been passing. Are you using any other different settings for the DB or special authentication settings?

**Comment by denkristoffer** [comment]
Nope, just the default MySQL 8 auth mode. The problem should be `mysql`: https://github.com/mysqljs/mysql/issues/1507, https://github.com/mysqljs/mysql/pull/2233, and many other issues on that repo.
