### ISSUE TITLE
Facebook login broken with some profile pics

### ISSUE THREAD

**Issue by WonderfulWorlds** [nextauthjs/adapters#173]
**Describe the bug**
Using TypeORM and MySQL, Facebook login fails for some users, as the url to their profile pics is longer than 255 characters. DB save operation fails.

**Steps to reproduce**
Try to save something longer than 255 characters in User.image

**Expected behavior**
No crashing due to any profile pic.

**Additional context**
I fixed it by increasing maximum allowed length of image string in UserSchema

```
image: {
      type: 'varchar',
      nullable: true,
      length: 1000
    },
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [X] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by ndom91** [comment]
Yeah I believe we increased the allowed length of that field a while back. I will close this issue for now. @WonderfulWorlds if you are still experiencing it, feel free to reopen.
