### ISSUE TITLE
Add support for firebase auth

### ISSUE THREAD

**Issue by HawKyre** [nextauthjs/adapters#180]
Hello, I wondered if it could be possible to add support for firebase auth in the firebase adapter, since it's also a part of the firebase ecosystem and right now everything is being handled by firestore.

**Comment by balazsorban44** [comment]
I don't see any API in Firebase Auth that makes it possible to create users programmatically. Am I wrong?

**Comment by balazsorban44** [comment]
Correction, I was reminded that there *is* an API! https://firebase.google.com/docs/auth/admin/manage-users I will look into it then!

**Comment by balazsorban44** [comment]
I would be happy if anyone interested in this could have a look as well. I am happy to give support.

**Comment by srijans38** [comment]
@balazsorban44  I'm interested in this. Just took a look. Found two issues with this so far:
1.  To integrate with Firebase Auth, we'd have to use "firebase-admin" which is a totally separate package from "firebase" web client and requires different setup.
2. What if someone wants to just use firestore as a db without firebase auth.
