### ISSUE TITLE
Google broken for new sign ups / account links

### ISSUE THREAD

**Issue by bduff9** [nextauthjs/adapters#184]
### Description 🐜

Why was this report moved to discussions?  https://github.com/nextauthjs/next-auth/discussions/2243

This seems to be a bug with either this library or something changed with Google.  For some reason, the error logs for this do not show up when running in a non-local env, but in local, the following gets printed:

```
[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error QueryFailedError: Column 'AccountAccessTokenExpires' cannot be null
    at new QueryFailedError (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/typeorm/error/QueryFailedError.js:12:28)
    at Query.onResult (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:217:45)
    at Query.execute (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/commands/command.js:31:14)
    at PoolConnection.handlePacket (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-fe/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:505:15)
    at addChunk (_stream_readable.js:286:12) {
  message: "Column 'AccountAccessTokenExpires' cannot be null",
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlState: '23000',
  sqlMessage: "Column 'AccountAccessTokenExpires' cannot be null",
  sql: "INSERT INTO `Accounts`(`AccountID`, `AccountCompoundID`, `UserID`, `AccountProviderType`, `AccountProviderID`, `AccountProviderAccountID`, `AccountRefreshToken`, `AccountAccessToken`, `AccountAccessTokenExpires`, `AccountAdded`, `AccountUpdated`, `AccountAddedBy`, `AccountUpdatedBy`) VALUES (DEFAULT, '4...eb', 1, 'oauth', 'google', '107...63', DEFAULT, 'ya..._X', NULL, DEFAULT, DEFAULT, 'NEXT_AUTH', 'NEXT_AUTH')",
  name: 'QueryFailedError',
  query: 'INSERT INTO `Accounts`(`AccountID`, `AccountCompoundID`, `UserID`, `AccountProviderType`, `AccountProviderID`, `AccountProviderAccountID`, `AccountRefreshToken`, `AccountAccessToken`, `AccountAccessTokenExpires`, `AccountAdded`, `AccountUpdated`, `AccountAddedBy`, `AccountUpdatedBy`) VALUES (DEFAULT, ?, ?, ?, ?, ?, DEFAULT, ?, ?, DEFAULT, DEFAULT, ?, ?)',
  parameters: [
    '4d...eb',
    1,
    'oauth',
    'google',
    '10...63',
    'ya..._X',
    null,
    'NEXT_AUTH',
    'NEXT_AUTH'
  ]
}
```

If I manually change my AccountAccessTokenExpires column to allow nulls, it works again.  And if I had an account that was linked before, it can be used to log in even without the null change.  But whatever this change is seems to have broken all new Google logins completely without modifying the Accounts database table.

### Is this a bug in your own project?

No

### How to reproduce ☕️

https://codesandbox.io/s/next-auth-example-1kktb

Go to your codesandbox example, and click log in with Google

### Environment 🖥

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 90.44 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 93.0.4577.42
    Firefox Developer Edition: 89.0
    Safari: 14.0.3
  npmPackages:
    next: 11.1.0 => 11.1.0 
    next-auth: <3.18.0 => 3.17.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The log message you pasted suggests that your schema doesn't allow `AccountAccessTokenExpires` be null, which it should.

**Comment by ndom91** [comment]
Yeah looks like maybe your DB is still the old original schema, and now doesn't match the updated adapter which now has a different schema / writes different things to various fields. 

We probably need to adjust the schema to allow NULLs here. 

Long term we probably need to provide migration scripts for the db to do this for people. The underlying structure of the db didn't change, but field types may have. 

Which adapter are you using exactly?

**Comment by bduff9** [comment]
@ndom91 Correct, typeorm and yes using version 3.17.2 of next auth.  I did make the change to allow nulls here but worried what else might have changed. I had to lock my next auth version to pre-3.18 cause that version broke my entire app beyond repair (at least in the couple hours I spent on trying to repair it).  So not sure where this change came from or when exactly it came in as I do have users who registered/linked google accounts previously.  This was just something that was reported to me earlier this week that it stopped working and I was able to replicate and eventually get the logging, but only from local.  Zero logging of this issue shows in prod anywhere I collect application logs.

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/pull/1862

was the PR that came after `3.17.2` and if I recall, even if it was intended to be an internal change, I think we needed to release some patches. Could you please try upgrading to the latest (`3.28.0` as of writing) version and see if that helps?
