### ISSUE TITLE
Support for Prisma MongoDB

### ISSUE THREAD

**Issue by Gitter499** [nextauthjs/adapters#195]
### Question 💬

Hi all,

I want to use next-auth with Prisma. I currently have Prisma setup with MongoDB.

I wanted to know if support for MongoDB has been added in the Prisma adapter. Since MongoDB support in Prisma is new, I don't know if the adapter has to be updated or it will work regardless. Many thanks! 

Docs: https://next-auth.js.org/adapters/prisma

### How to reproduce ☕️

Create a nextjs project with `npx create-next-app`, add Prisma and next-auth as dependencies. Then, set the Prisma provider to MongoDB. Finally, install the next-auth Prisma adapter.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Have you actually tried using mongoDB, or just asking?

**Comment by Gitter499** [comment]
I am asking because I am not sure if it would work with my current setup. There’s no official wording of MongoDB with Prisma in the docs.

**Comment by balazsorban44** [comment]
Yeah, I am not sure either. :smile: you should try :wink:
