### ISSUE TITLE
prisma-adapter@0.4.4-canary.81 overrides automatic User ID generation

### ISSUE THREAD

**Issue by kripod** [nextauthjs/adapters#200]
Comparing `@next-auth/prisma-adapter@0.4.4-canary.41` to `@next-auth/prisma-adapter@0.4.4-canary.81`, I came across the following difference:

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/14854048/131672978-2e0303ac-6224-4109-85dd-dfa3c589a843.png">

The `profile` variable should not be spread in the user creation mechanism, as it overrides the DB’s custom ID generation mechanism and thus, collisions may happen between providers and the IDs are no longer K-sortable as a result. I think this change should be reverted.

**Comment by kripod** [comment]
It turns out this has been fixed in v0.5.3. Apologies for the nuisance.

**Comment by balazsorban44** [comment]
This has been fixed/reverted in #166. Please upgrade to at least `@next-auth/prisma-adapter@0.5.3`
