### ISSUE TITLE
Where is the provided SQL for Prisma adapter?

### ISSUE THREAD

**Issue by Gugols** [nextauthjs/adapters#204]
### Question 💬

Hi, looking at [https://next-auth.js.org/adapters/prisma](https://next-auth.js.org/adapters/prisma)
there is a note:

> While Prisma includes an experimental feature in the migration command that is able to generate SQL from a schema, creating tables and columns **using the provided SQL** is currently recommended instead as SQL schemas automatically generated by Prisma may differ from the recommended schemas.

Where the provided .sql can be found? Since indeed, for me after the generating, migrating and introspecting again, it changes schema.prisma to something different and breaks the app which initially works.

>Unknown arg `providerId_providerAccountId` in where.providerId_providerAccountId for type AccountWhereUniqueInput.

### How to reproduce ☕️

-

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Which Prisma adapter are you using? please provide some more information.

the docs comment there is old and should probably be removed. you are better off using `prisma migrate`

**Comment by 2color** [comment]
Hey @Gugols 👋,
The docs are outdated. Assuming that you're using the latest Prisma adapter (`@next-auth/prisma-adapter`), I would try using `npx prisma migrate dev` (if in local development) to create the migration and run the migration and `npx prisma migrate deploy` to deploy the created migration in production.

**Comment by balazsorban44** [comment]
This is addressed in https://github.com/nextauthjs/docs/pull/6
