### ISSUE TITLE
getUserByAccount is not a function

### ISSUE THREAD

**Issue by allealdine** [nextauthjs/adapters#208]
### Description 🐜

I am sure the following is bug:
```sh
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error getUserByAccount is not a function {
  message: 'getUserByAccount is not a function',
  stack: 'TypeError: getUserByAccount is not a function\n' +
    '    at Object.callback (webpack-internal:///./node_modules/next-auth/server/routes/callback.js:71:39)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
    '    at async NextAuthHandler (webpack-internal:///./node_modules/next-auth/server/index.js:169:18)\n' +
    '    at async apiResolver (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/api-utils.js:8:1)\n' +
    '    at async DevServer.handleApiRequest (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/next-server.js:66:462)\n' +
    '    at async Object.fn (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/next-server.js:58:580)\n' +
    '    at async Router.execute (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/router.js:25:67)\n' +
    '    at async DevServer.run (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/next-server.js:68:1042)\n' +
    '    at async DevServer.handleRequest (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/next-server.js:32:504)',
  name: 'TypeError'
}
```
### Is this a bug in your own project?

No

### How to reproduce ☕️

Signin with google account and error occurred right after user google acceptance.

### Screenshots / Logs 📽
```sh
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error getUserByAccount is not a function {
  message: 'getUserByAccount is not a function',
  stack: 'TypeError: getUserByAccount is not a function\n' +
    '    at Object.callback (webpack-internal:///./node_modules/next-auth/server/routes/callback.js:71:39)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
    '    at async NextAuthHandler (webpack-internal:///./node_modules/next-auth/server/index.js:169:18)\n' +
    '    at async apiResolver (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/api-utils.js:8:1)\n' +
    '    at async DevServer.handleApiRequest (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/next-server.js:66:462)\n' +
    '    at async Object.fn (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/next-server.js:58:580)\n' +
    '    at async Router.execute (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/router.js:25:67)\n' +
    '    at async DevServer.run (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/next-server.js:68:1042)\n' +
    '    at async DevServer.handleRequest (/Users/allealdine/ReactJS/mymedi/web/node_modules/next/dist/next-server/server/next-server.js:32:504)',
  name: 'TypeError'
}
```
### Environment 🖥

  System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 1.08 GB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 14.1.2
  npmPackages:
    next: ^11.0.1 => 11.0.1 
    next-auth: 4.0.0-beta.1 => 4.0.0-beta.1 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Which adapter are you using? Make sure it is also upgraded https://next-auth.js.org/getting-started/upgrade-v4#adapters

**Comment by allealdine** [comment]
Hi balaz, I followed the upgrade (see below), but may be I took wrong version: "@next-auth/typeorm-legacy-adapter": "^0.1.4". However, I could not find any suitable version of @next-auth/typeorm-legacy-adapter yet to connect to postgresql. 

`
import NextAuth from "next-auth";
import { TypeORMLegacyAdapter } from "@next-auth/typeorm-legacy-adapter";
import EmailProvider from "next-auth/providers/email";
import GoogleProvider from "next-auth/providers/google";

const options = {
    providers: [
        EmailProvider({
            server: process.env.EMAIL_SERVER,
            from: process.env.EMAIL_FROM,
        }),
        GoogleProvider({
            clientId: process.env.GOOGLE_ID,
            clientSecret: process.env.GOOGLE_SECRET,
        }),
    ],
    adapter: TypeORMLegacyAdapter(process.env.NEXT_PUBLIC_DATABASE_URL),
    ...
}
`
Here is the .env:

NEXT_PUBLIC_DATABASE_URL=postgres://strapi_pgdb:strapi_pgdb@localhost:5432/strapi_pgdb?synchronize=true

**Comment by balazsorban44** [comment]
As stated in the migration docs above, you should be using the `next` channel when upgrading your adapter. Currently that means this version for  typeorm: https://www.npmjs.com/package/@next-auth/typeorm-legacy-adapter/v/0.1.2-next.8

**Comment by duyet** [comment]
I got the same issue with the Prisma adapter. I'm using the `4.0.0-beta.1` version of next-auth and the latest `0.5.4` version of [@next-auth/prisma-adapter](https://github.com/nextauthjs/adapters/releases/tag/%40next-auth%2Fprisma-adapter%400.5.4). 
I believe the required method for adapters has changed, according to this [document](https://next-auth.js.org/tutorials/creating-a-database-adapter), but the adapter not updated yet.  

```
ext-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error getUserByAccount is not a function {
  message: 'getUserByAccount is not a function',
  stack: 'TypeError: getUserByAccount is not a function\n' +
    '    at Object.callback (webpack-internal:///./node_modules/next-auth/server/routes/callback.js:71:39)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
    '    at async NextAuthHandler (webpack-internal:///./node_modules/next-auth/server/index.js:171:18)\n' +
    '    at async eval (webpack-internal:///./node_modules/next-auth/server/index.js:251:32)\n' +
    '    at async Object.apiResolver (/Users/duyet/project/cit-feedback/node_modules/next/dist/server/api-utils.js:101:9)\n' +
    '    at async DevServer.handleApiRequest (/Users/duyet/project/cit-feedback/node_modules/next/dist/server/next-server.js:760:9)\n' +
    '    at async Object.fn (/Users/duyet/project/cit-feedback/node_modules/next/dist/server/next-server.js:651:37)\n' +
    '    at async Router.execute (/Users/duyet/project/cit-feedback/node_modules/next/dist/server/router.js:205:32)\n' +
    '    at async DevServer.run (/Users/duyet/project/cit-feedback/node_modules/next/dist/server/next-server.js:825:29)',
  name: 'TypeError'
}
```

**Comment by balazsorban44** [comment]
Again, please read the documentation I linked to!

https://next-auth.js.org/getting-started/upgrade-v4#adapters

![](https://i.imgur.com/tzTmSvc.png)
