### ISSUE TITLE
[MongoDB Adapter] Type 'Db' is not assignable to type '() => Db'

### ISSUE THREAD

**Issue by lukvermeulen** [nextauthjs/adapters#210]
I am currently testing with `next-auth v4 beta` and trying to implement the MongoDB Adapter mentionend in this example: [https://next-auth.js.org/adapters/mongodb](https://next-auth.js.org/adapters/mongodb)

My `lib/mongodb` looks like this: 

```ts
import { MongoClient, MongoClientOptions } from "mongodb";

if (!process.env.MONGODB_URI) {
    throw new Error("Please add your Mongo URI to .env.local");
}

const uri = process.env.MONGODB_URI;

const options: MongoClientOptions = {
    //@ts-ignore
    useUnifiedTopology: true,
    useNewUrlParser: true,
};

let client: MongoClient;
let clientPromise: Promise<MongoClient>;

if (process.env.NODE_ENV === "development") {
    // In development mode, use a global variable so that the value
    // is preserved across module reloads caused by HMR (Hot Module Replacement).
    //@ts-ignore
    if (!global._mongoClientPromise) {
        client = new MongoClient(uri, options);
        // @ts-ignore
        global._mongoClientPromise = client.connect();
    }
    //@ts-ignore
    clientPromise = global._mongoClientPromise;
} else {
    // In production mode, it's best to not use a global variable.
    client = new MongoClient(uri, options);
    clientPromise = client.connect();
}

// Export a module-scoped MongoClient promise. By doing this in a
// separate module, the client can be shared across functions.
export default clientPromise;
```
I declared clientPromise as Promise<MongoClient>, so it is not implicitly any and changed the order of statements a bit (e.g checking if process.env.MONGODB_URI exists before assigning it to something).

My `api/auth/[...nextauth].ts`

looks like this:

```ts
import NextAuth, { Session, User } from "next-auth";
import GithubProvider from `next-auth/providers/github`;
import { MongoDBAdapter } from "@next-auth/mongodb-adapter";
import clientPromise from "../../../lib/mongodb";

export default NextAuth({
    providers: [
        GithubProvider({
            clientId: process.env.GITHUB_CLIENT_ID,
            clientSecret: process.env.GITHUB_CLIENT_SECRET,
        }),
    ],
    adapter: MongoDBAdapter({
        db: (await clientPromise).db("your-database"),
    }),
});
```

TS has the following error with the line `db: (await clientPromise).db("your-database"),`:

```sh
Type 'Db' is not assignable to type '() => Db'.
  Type 'Db' provides no match for the signature '(): Db'.ts(2322)
index.d.ts(14, 5): The expected type comes from property 'db' which is declared here on type '{ db: () => Db; ObjectId: typeof ObjectId; }'
```

If anyone has a suggestion on how to fix this, that would be much appreciated!

**Comment by balazsorban44** [comment]
Thank you for the code example!

If you followed the [`README.md`](https://github.com/nextauthjs/adapters/tree/next/packages/mongodb#getting-started):

```ts
import NextAuth from "next-auth"
import Providers from "next-auth/providers"
import { MongoDBAdapter } from "@next-auth/mongodb-adapter"
import clientPromise from "lib/mongodb"

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export default async function auth(req, res) {
  return await NextAuth(req, res, {
    adapter: MongoDBAdapter({
      db: (await clientPromise).db("your-database")
    }),
    // https://next-auth.js.org/configuration/providers
    providers: [
      Providers.Google({
        clientId: process.env.GOOGLE_ID,
        clientSecret: process.env.GOOGLE_SECRET,
      }),
    ],
    ...
  })
}
```

Your issue is a JavaScript one. Basically, the way you are using `NextAuth` hides the `(req, res) => {}` part. But since there is an `await`, there has to be an `async` as well. Hence the wrapper.

This is needed because the MongoClient doesn't handle connections automatically.

**Comment by lukvermeulen** [comment]
Hi Balazs, thanks for the quick response and link to the readme, I hadn't found that one yet.

I changed my Code to look like this now:

```
export default async function auth(req: NextApiRequest, res: NextApiResponse) {
    return await NextAuth(req, res, {
        adapter: MongoDBAdapter({
            db: (await clientPromise).db("your-database"),
        }),
        providers: [
            GithubProvider({
                clientId: process.env.GITHUB_CLIENT_ID,
                clientSecret: process.env.GITHUB_CLIENT_SECRET,
            }),
        ],
    });
}
```

but sadly the TS error does not change. Sorry if I am missing something obvious here.

If I remove my own TS additions from `lib/mongodb`, the TS error looks like this: 

```
Argument of type '{ db: any; }' is not assignable to parameter of type '{ db: () => Db; ObjectId: typeof ObjectId; }'.
  Property 'ObjectId' is missing in type '{ db: any; }' but required in type '{ db: () => Db; ObjectId: typeof ObjectId; }'.ts(2345)
index.d.ts(15, 5): 'ObjectId' is declared here.
Variable 'clientPromise' implicitly has an 'any' type.ts(7005)
```
with my additions: 

```
Type 'Db' is not assignable to type '() => Db'.
  Type 'Db' provides no match for the signature '(): Db'.ts(2322)
index.d.ts(14, 5): The expected type comes from property 'db' which is declared here on type '{ db: () => Db; ObjectId: typeof ObjectId; }'
```

**Comment by balazsorban44** [comment]
Just curious, what is the version of your `@next-auth/mongodb-adapter`?

**Comment by lukvermeulen** [comment]
Indeed, manually updating to `0.0.2-next.276` solves this issue. Thanks alot!

**Comment by MZ071999** [comment]
> Thank you for the code example!
> 
> If you followed the [`README.md`](https://github.com/nextauthjs/adapters/tree/next/packages/mongodb#getting-started):
> 
> ```ts
> import NextAuth from "next-auth"
> import Providers from "next-auth/providers"
> import { MongoDBAdapter } from "@next-auth/mongodb-adapter"
> import clientPromise from "lib/mongodb"
> 
> // For more information on each option (and a full list of options) go to
> // https://next-auth.js.org/configuration/options
> export default async function auth(req, res) {
>   return await NextAuth(req, res, {
>     adapter: MongoDBAdapter({
>       db: (await clientPromise).db("your-database")
>     }),
>     ...
>   })
> }
> ```
> 
> Your issue is a JavaScript one. Basically, the way you are using `NextAuth` hides the `(req, res) => {}` part. But since there is an `await` on `clientPromise`, there has to be an `async` above it as well. Hence the `auth` wrapper function.
> 
> This is needed because the MongoClient doesn't handle connections automatically, like Prisma for example. 🤷

hi, I am doing exactly like this but got an error:
"TypeError: db is not a function"
