### ISSUE TITLE
Upgrade mongodb dependency to v4?

### ISSUE THREAD

**Issue by joniaiuser** [nextauthjs/adapters#218]
### Question 💬

Wondering if next-auth team will upgrade the mongodb node driver dependency to v4 (current major version)? As ODMs such as mongoose as upgraded to using that so there are some incompatibility issues when trying to use next-auth with mongoose latest version. 

https://mongoosejs.com/docs/migrating_to_6.html#mongodb-driver-40

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
No, not for v3. v4 will have its own MongoDB-specific adapter (that supports newer mongodb versions). And this has already been answered in #192

See the new adapter docs as well: https://next-auth.js.org/adapters/mongodb
And a migration guide from v3 to v4: https://next-auth.js.org/getting-started/upgrade-v4
