### ISSUE TITLE
getUserByAccount is not a function - next auth & prisma google provider

### ISSUE THREAD

**Issue by joshua-isaac** [nextauthjs/adapters#220]
### Description 🐜

Using `next-auth@4.0.0-beta.2` with `prisma` and `@next-auth/prisma-adapter`, I get an error trying to authenticate with the google provider

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

set up next-auth:

```
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
});
```

### Screenshots / Logs 📽

![Screen Shot 2021-09-12 at 8 51 19 PM](https://user-images.githubusercontent.com/40035381/133009259-67b514d2-bc90-485a-9157-e5fe82f421e2.png)

### Environment 🖥

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 846.43 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 84.0.2
    Safari: 14.0.1
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: 4.0.0-beta.2 => 4.0.0-beta.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by AydinChavez** [comment]
Thanks, didn't know about the adapter repo.
Since lot of user complained about this same topic / error message (including me) although being documented, maybe it helps to explicitly mention prisma as an example there as well (assuming some users are using simply ctrl+f for searching about related migration hints - here prisma).

```
WARNING
When using the NextAuth v4 beta, please be sure to use the next tagged version of your adapter. 
For example, to use the appropriate typeorm version with NextAuth v4, you would install @next-auth/typeorm-legacy-adapter@next.
```

```
WARNING
When using the NextAuth v4 beta, please be sure to use the next tagged version of your adapter. 
For example, to use the appropriate typeorm version with NextAuth v4, you would install @next-auth/typeorm-legacy-adapter@next. 
For prisma, you would install @next-auth/prisma-adapter@next (you can check https://www.npmjs.com/package/@next-auth/prisma-adapter for the latest next package).
```

**Comment by balazsorban44** [comment]
we have a growing number of adapters, and cannot name each of them, or at least it doesn't really make sense to me. @ndom91 what do you think?

I think carefully reading the whole migration document will make you aware of the issue at hand.

I might have come off as a bit harsh and I'm sorry for that, but you have to understand as a maintainer it's frustrating to answer the same questions, especially when we already documented the solution.

The beta period is a bit special I understand, but as `beta` suggests, you might encounter small issues, and we have to assume that people who try it out are willing to get their hands at least a bit more dirty!

That said, I'm terrible at keeping a monorepo to semantic versioning, and I really hope that after a stable v4 release it is going to be easier. 😬 So I can acknowledge at least part of the confusion. :green_heart:
