### ISSUE TITLE
[V4] TypeORM-legacy adapter connection not being set correctly

### ISSUE THREAD

**Issue by Fronix** [nextauthjs/adapters#222]
I believe the next version of [typeorm-legacy-adapter ](https://github.com/nextauthjs/adapters/tree/next/packages/typeorm-legacy) has a broken connection manager. 

Currently, it looks like the connection will never be able to hold the `default` connection, as it always defaults to trying to create a new connection. Not exactly sure why this happens. This results in the `A connection with the name "default" already exists` error

I solved this by writing a utility function `ensureConnection` and also add the "has entities changed" check.

```typescript
function entitiesChanged(prevEntities: any, newEntities: any[]): boolean {
  if (prevEntities?.length !== newEntities?.length) return true;

  for (let i = 0; i < prevEntities?.length; i++) {
    if (prevEntities[i] !== newEntities[i]) return true;
  }

  return false;
}

export async function updateConnectionEntities(connection: Connection, entities: any[]) {
  if (!entitiesChanged(connection.options.entities, entities)) return;

  // @ts-ignore
  connection.options.entities = entities;

  // @ts-ignore
  connection.buildMetadatas();

  if (connection.options.synchronize) {
    await connection.synchronize()
  }
}

export async function ensureConnection(_connection: Connection, config: ConnectionOptions & { entities: any[]}) {
  const connectionManager = getConnectionManager();

  if (connectionManager.has('default')) {
    _connection = connectionManager.get();

    _connection.isConnected || (await _connection.connect());

    if (process.env.NODE_ENV !== 'production') {
      await updateConnectionEntities(_connection, config.entities);
    }
  } else {
    _connection = await connectionManager.create(config).connect();
  }

  return _connection.manager;
}

```

**getManager** now looks like this
```typescript
...
export async function getManager(options: {
  connection: string | ConnectionOptions;
  entities: Entities;
}): Promise<EntityManager> {
  const { connection, entities } = options;

  const config = {
    ...parseConnectionConfig(connection),
    entities: Object.values(entities)
  };

  return await ensureConnection(_connection, config);
}
...
```

**Comment by balazsorban44** [comment]
Why would entities change? I would assume you don't want to synchronize in production (which is not recommended)? Am I missing something?

**Comment by Fronix** [comment]
@balazsorban44 
I think your tests work because you only run the db functions from the next-auth package. When creating your own adapter using typeorm and calling the adapter from `[...next-auth].ts` file for some custom db checks on for example `signIn` the db error occurs.

Here is a fully functional reproduction: https://github.com/Fronix/next-auth-adapter--222
It's setup for MSSQL since that's what we use. It might be a very specific scenario, but I think it's still relevant and should be addressed, since it works fine with V3 using the same setup.

I'd be happy to make a PR however I think you have a valid point of reusing the previous connection which I'm not sure is done here since it calls `connect()` either way.

And yes there should be a warning in the console when the DB is synced, and also an explanation of what error that is :)

**Comment by Fronix** [comment]
On second thought, it might be as simple as returning the manager is `isConnected` is true. Teste it right now and it seemed to work.

```typescript
export async function ensureConnection(_connection: Connection, config: ConnectionOptions & { entities: any[]}) {
  const connectionManager = getConnectionManager();

  if (connectionManager.has('default')) {
    _connection = connectionManager.get();

    //_connection.isConnected || (await _connection.connect());
   if (_connection.isConnected) return _connection.manager

    if (process.env.NODE_ENV !== 'production') {
      await updateConnectionEntities(_connection, config.entities);
    }
  } else {
    _connection = await connectionManager.create(config).connect();
  }

  return _connection.manager;
}
```

**Comment by balazsorban44** [comment]
I tested it on a local app also, and everything seemed to work for me, but I'll have a look at your reproduction.
