### ISSUE TITLE
Email Adapter - Cannot read property 'create' of undefined "CreateVerificationTokenError"

### ISSUE THREAD

**Issue by fefe-x** [nextauthjs/adapters#231]
### Question 💬

Hey,

when using only email provider, I get the following error after submitting an email on the signin page:

```sh
[next-auth][error][adapter_error_createVerificationToken]
https://next-auth.js.org/errors#adapter_error_createverificationtoken Cannot read property 'create' of undefined {
  message: "Cannot read property 'create' of undefined",
  stack: "TypeError: Cannot read property 'create' of undefined\n" +
    '    at createVerificationToken (*/node_modules/@next-auth/prisma-adapter/dist/index.js:34:64)\n' +
    '    at Object.acc.<computed> [as createVerificationToken] (*/.next/server/pages/_app.js:1177:22)\n' +
    '    at email (*/.next/server/pages/api/auth/[...nextauth].js:1572:17)\n' +
    '    at async Object.signin (*/.next/server/pages/api/auth/[...nextauth].js:3284:7)\n' +
    '    at async NextAuthHandler (*/.next/server/pages/api/auth/[...nextauth].js:946:18)\n' +
    '    at async */.next/server/pages/api/auth/[...nextauth].js:995:32\n' +
    '    at async Object.apiResolver (*/node_modules/next/dist/server/api-utils.js:101:9)\n' +
    '    at async DevServer.handleApiRequest (*/node_modules/next/dist/server/next-server.js:770:9)\n' +
    '    at async Object.fn (*/node_modules/next/dist/server/next-server.js:661:37)\n' +
    '    at async Router.execute (*/node_modules/next/dist/server/router.js:205:32)',
  name: 'TypeError'
}
```

I've tried several [...nextauth].js configs (basic ones like this, also what I used to use before v4). Would greatly appreciate any help!
next-auth version: "next-auth": "4.0.0-beta.2",
adapter version: "@next-auth/prisma-adapter": "^0.5.2-next.5",

### How to reproduce ☕️

This is my [...nextauth].js file:
```js
import prisma from '../../../lib/prisma'

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    EmailProvider({
      server: {
        host: process.env.EMAIL_SERVER_HOST,
        port: Number(process.env.EMAIL_SERVER_PORT),
        auth: {
          user: process.env.EMAIL_SERVER_USER,
          pass: process.env.EMAIL_SERVER_PASSWORD
        }
      },
      from: process.env.EMAIL_FROM
    }),
  ],
})
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Could you show how `prisma` looks like that you import like this?:
```
import prisma from '../../../lib/prisma'
```

**Comment by fefe-x** [comment]
Hey 👋

It's simply imported so the prisma db connection gets reused when possible.
```import { PrismaClient } from "@prisma/client";

// PrismaClient is attached to the `global` object in development to prevent
// exhausting your database connection limit.
//
// Learn more: 
// https://pris.ly/d/help/next-js-best-practices

declare global {
  namespace NodeJS {
    interface Global {
      prisma: any;
    }
  }
}

let prisma: PrismaClient

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient()
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient()
  }
  prisma = global.prisma
}
export default prisma```

**Comment by balazsorban44** [comment]
The error you are showing suggests that `prisma.verificationToken` is undefined, which I think can happen if you forgot to run `prisma generate`. Can this be the case?

**Comment by fefe-x** [comment]
I don't think so, prisma client is definitely generated. I tried this in production with "postinstall": "prisma generate" set in package.json as well.

**Comment by balazsorban44** [comment]
so if you log out `prisma.verificationToken`, it's never undefined? I don't see any other reasons for this to fail

**Comment by fefe-x** [comment]
Managed to fix it, was related to the database schema not being correct. Thank you for your quick replies, great work on v4!

**Comment by balazsorban44** [comment]
awesome, and thanks!

**Comment by Rade58** [comment]
I am having same problem after updating to version 4.0.0-beta.4 .
For example, google OAuth works perfectly fine, but email doesn't, it throws the same error.
I updated schema according to documentation for v4, didn't find any inconsistencies there.
@fefe-x can you explain what you fixed in your schema?
