### ISSUE TITLE
How to use custom models/Modify the user model with MongoDBAdapter?

### ISSUE THREAD

**Issue by bklynate** [nextauthjs/adapters#232]
### Question 💬

Is it possible to modify the user model with the MongoDBadapter by adding additional fields?

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Mongodb being a nosql database doesn't uses models, so technically you can save anything. We don't enforce a structure. 

If you need to add extra fields to the User, that will be determined what your Provider's `profile` callback returns. 

See:

https://next-auth.js.org/adapters/models#user

https://docs.mongodb.com/manual/core/data-modeling-introduction/#flexible-schema

**Comment by bklynate** [comment]
Can you provide a working example? perhaps we could update the ReadMe with an example?

**Comment by balazsorban44** [comment]
there is really nothing to it, as said there is no enforced models. let's say your provider gives you a role you want to save on the user:

```js
...
providers: [
  YourProvider({
    ... 
    profile(profile) {
      return {
         id: profile.sub,
         name: profile.name,
         image: profile.picture,
         email: profile.email,
         role: profile.role
      } 
]
...
```
