### ISSUE TITLE
i am getting this Message "Try signing in with a different account"

### ISSUE THREAD

**Issue by zadigg** [nextauthjs/adapters#251]
Repository: https://github.com/zadigg/googleDocClon

I am using nextauth for authentication through Google, and it's telling me  to sign with different acc, 
What does it Mean? and What does it matter as long as the redirect URIs works

*You can see it here that redirect URIs works
![image](https://user-images.githubusercontent.com/62830716/134033913-54d1c994-31aa-4794-8f49-68136d29f33b.png)

And when you try to log in I get this message, I even tried to sign in with another account but the same problem occurs

![image](https://user-images.githubusercontent.com/62830716/134034073-3f01c90a-bd34-4012-a976-97af75b35739.png)

#83 I checked this issue but it's not helping

**Comment by balazsorban44** [comment]
without a reproduction, it's hard to help you. could you create a repository recreating your problem?

**Comment by zadigg** [comment]
> without a reproduction, it's hard to help you. could you create a repository recreating your problem?


https://github.com/zadigg/googleDocClon

**Comment by geovanisouza92** [comment]
I'm getting the same with DynamoDB.

<details>
<summary>Error from DocumentClient</summary>
```sh
[AWS dynamodb 400 0.015s 0 retries] updateItem({
  TableName: 'table-name-here',
  Key: {
    pk: { S: 'USER#6a6ec5ac6818b9e1b5bc56dc04f47742' },
    sk: { S: 'USER#6a6ec5ac6818b9e1b5bc56dc04f47742' }
  },
  UpdateExpression: 'set #name = :name, #email = :email, #gsi1pk = :gsi1pk, #gsi1sk = :gsi1sk, #image = :image, #emailVerified = :emailVerified, #username = :username, #updatedAt = :updatedAt',
  ExpressionAttributeNames: {
    '#name': 'name',
    '#email': 'email',
    '#gsi1pk': 'GSI1PK',
    '#gsi1sk': 'GSI1SK',
    '#image': 'image',
    '#emailVerified': 'emailVerified',
    '#username': 'username',
    '#updatedAt': 'updatedAt'
  },
  ExpressionAttributeValues: {
    ':name': null,
    ':email': { S: 'foo2@example.com' },
    ':gsi1pk': { S: 'USER#foo2@example.com' },
    ':gsi1sk': { S: 'USER#foo2@example.com' },
    ':image': null,
    ':emailVerified': { S: '2021-09-20T22:50:46.114Z' },
    ':username': null,
    ':updatedAt': { S: '2021-09-20T22:50:46.114Z' }
  },
  ReturnValues: 'UPDATED_NEW'
})
[next-auth][error][dynamodb__update_user_error] 
https://next-auth.js.org/errors#dynamodb__update_user_error ValidationException: Invalid UpdateExpression: An expression attribute value used in expression is not defined; attribute value: :username
```
</details>

The problem seems to be that the adapter is using null as values for some attributes.

**Comment by balazsorban44** [comment]
a complete refractor for v4 is on the way in #238 with sane defaults and expandability in mind, with tests for more confidence from our side.

**Comment by balazsorban44** [comment]
Depends. I have a full-time job. Feel free to use the code in the PR, but be aware it is not tested on our side whatsoever. Also, the previous comment I responded to was removed, #238 is about DynamoDB, OP had an issue with Firebase. That said, the Firebase Adapter is also being refactored #183.
