### ISSUE TITLE
DynamoDB adapter should use TTL

### ISSUE THREAD

**Issue by geovanisouza92** [nextauthjs/adapters#252]
## Context

Currently the only way to expire _verification tokens_ and _sessions_ is waiting until one of them get read and [check](https://github.com/nextauthjs/adapters/blob/26cd24a6eba3d42ed7febd5eb45b13c236c57819/packages/dynamodb/src/index.ts#L261) if it's [expired](https://github.com/nextauthjs/adapters/blob/26cd24a6eba3d42ed7febd5eb45b13c236c57819/packages/dynamodb/src/index.ts#L415).

This is not a good design, because DynamoDB have the [TTL feature](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html) for scenarios like this one.

## Proposed change

- Change the [`createSession`](https://github.com/nextauthjs/adapters/blob/26cd24a6eba3d42ed7febd5eb45b13c236c57819/packages/dynamodb/src/index.ts#L234) method to include an attribute `ttl` with the unix epoch representation of the `expires` attribute.
- Change the [`createVerificationRequest`](https://github.com/nextauthjs/adapters/blob/26cd24a6eba3d42ed7febd5eb45b13c236c57819/packages/dynamodb/src/index.ts#L385) method to include an attribute `ttl` with the unix epoch representation of the `expires` attribute.
- Update the documentation about the possibility, so users of the adapter could configure TTL on their tables.
- Optional: Make the `ttl` attribute name configurable.

**Comment by anthonyringoet** [comment]
I think this can be closed as https://github.com/nextauthjs/adapters/pull/268 was merged.
