### ISSUE TITLE
Custom model/user property in V4

### ISSUE THREAD

**Issue by vahidtakro** [nextauthjs/adapters#287]
### Question 💬

Hello, how can I add custom model on v4?
I am using Prisma provider, and I added new column to User table, called username,
I want to get `{session.user.username}` how can I add username property?

### How to reproduce ☕️

now I get this error:
![Screenshot 2021-10-30 143726](https://user-images.githubusercontent.com/40500566/139530582-a69b7f5b-be10-41ac-9e79-26932991d2b2.jpg)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by vahidtakro** [comment]
> https://next-auth.js.org/getting-started/typescript

in fact I am using js, not ts. can I do that with js?

**Comment by balazsorban44** [comment]
Not sure what you mean, you are showing a TypeScript error?

**Comment by vahidtakro** [comment]
> Not sure what you mean, you are showing a TypeScript error?

no, this error happens in JS file, I don't use TypeScript in my project.

**Comment by balazsorban44** [comment]
I don't see the problem then. What you are showing on your picture is a TS error reported by VSCode Intellisense, I believe. If you are using JS, just ignore it.

**Comment by vahidtakro** [comment]
> I don't see the problem then. What you are showing on your picture is a TS error reported by VSCode Intellisense, I believe. If you are using JS, just ignore it.

Just tried with both ts and js, there is no way to show username, biography, and other manually-added strings, I even created the file in types, still not working. Do I need to do something extra?

**Comment by balazsorban44** [comment]
I don't understand the problem. do you have a reproduction?

**Comment by vahidtakro** [comment]
> I don't understand the problem. do you have a reproduction?

Let me explain you,
1. I created auth system with version 4,
2. And I use Prisma as the provider to store user data,
3. I created user profiles to display user data, such as profile image, email, name, biography, username, ...
4. And now I am creating user dashboard, to let user customize his profile, like changing username, image, email,...
5. The problem is that I can not get custom strings to display on default values in forms, such as username. I can only get name, email, and image.

Do I need to do something special for that? Or is there any example as repo for that?

**Comment by balazsorban44** [comment]
Yes https://next-auth.js.org/configuration/callbacks#session-callback

**Comment by vahidtakro** [comment]
> Yes https://next-auth.js.org/configuration/callbacks#session-callback

sorry, I am just a basic learner, so I just copy-pasted the code, in my nextauth, but now I can not log in anymore:

```
// pages/api/auth/[...nextauth].js

import NextAuth from 'next-auth'
import Auth0Provider from "next-auth/providers/auth0"
import GoogleProvider from "next-auth/providers/google"
import GithubProvider from "next-auth/providers/github"

import { PrismaAdapter } from "@next-auth/prisma-adapter"
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()


export default NextAuth({
  // Configure one or more authentication providers
  callbacks: {
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token from a provider.
      session.accessToken = token.accessToken
      return session
    }
  },
  adapter: PrismaAdapter(prisma),
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
    // ...add more providers here
  ],
})
```

**Comment by vahidtakro** [comment]
the problem solved like this:
```
  callbacks: {
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token from a provider.
      session.user.username = user.username
      return session
    }
  },
  ```
  so I can get the username in my app, and it works well. but the code still shows this error, is it a problem?
  
![Screenshot 2021-10-30 171738](https://user-images.githubusercontent.com/40500566/139535455-e794d111-bafa-47d9-ab63-bcbefe2afafe.jpg)

**Comment by balazsorban44** [comment]
again, that's something reported by your IDE, it's not an error in your code, just some smart suggestions. you aren't using TS as you said, so just ignore that. I sent you the link how to do it in case you want to use TS

**Comment by vahidtakro** [comment]
@balazsorban44 Thanks! anyway the app is working well now, koszonom!

**Comment by balazsorban44** [comment]
Szívesen! 💚
