### ISSUE TITLE
Account creation failed with GoogleProvider and Prisma

### ISSUE THREAD

**Issue by nechmads** [nextauthjs/adapters#289]
### Title

Account creation failed with GoogleProvider and Prisma

### How to reproduce ☕️

setup a new next js project with next-auth version 4.0.0-beta.6, Prisma client version 3.3.0 and @next-auth/prisma-adapter version 0.5.2-next.19 using MySql database.

Add the Google auth provider and try to signIn.

The signed user is added to the users table but the process is failing when trying to create the account.

### Your question/bug report 📓

When trying to sign in with Google, the user is added to the users table but the process fail with an error when trying to create the account on some field length issue.

I tried to convert the Account model to have archer(255) but the error didn't go away.
Here is the model for the account I used (taken from the docs with the archer change):
```prisma
model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String @db.VarChar(255)
  provider           String @db.VarChar(255)
  providerAccountId  String @db.VarChar(255)
  refresh_token      String? @db.VarChar(255)
  access_token       String? @db.VarChar(255)
  expires_at         Int?
  token_type         String? @db.VarChar(255)
  scope              String? @db.VarChar(255)
  id_token           String? @db.VarChar(255)
  session_state      String? @db.VarChar(255)
  oauth_token_secret String? @db.VarChar(255)
  oauth_token        String? @db.VarChar(255)

  user User @relation(fields: [userId], references: [id])

  @@unique([provider, providerAccountId])

}
```

```sh
**Error:**
Invalid `p.account.create()` invocation in
/Users/shahar/Projects/gallerium/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: (data) => p.user.update({ where: { id: data.id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create(
  The provided value for the column is too long for the column's type. Column: for
    at cb (/Users/shahar/Projects/gallerium/node_modules/@prisma/client/runtime/index.js:38537:17)
    at async acc.<computed> (/Users/shahar/Projects/gallerium/node_modules/next-auth/core/errors.js:92:16)
    at async callbackHandler (/Users/shahar/Projects/gallerium/node_modules/next-auth/core/lib/callback-handler.js:180:7)
    at async Object.callback (/Users/shahar/Projects/gallerium/node_modules/next-auth/core/routes/callback.js:117:13)
    at async NextAuthHandler (/Users/shahar/Projects/gallerium/node_modules/next-auth/core/index.js:103:28)
    at async NextAuthNextHandler (/Users/shahar/Projects/gallerium/node_modules/next-auth/next/index.js:40:7)
    at async /Users/shahar/Projects/gallerium/node_modules/next-auth/next/index.js:80:32
    at async Object.apiResolver (/Users/shahar/Projects/gallerium/node_modules/next/dist/server/api-utils.js:102:9)
    at async DevServer.handleApiRequest (/Users/shahar/Projects/gallerium/node_modules/next/dist/server/next-server.js:1017:9)
    at async Object.fn (/Users/shahar/Projects/gallerium/node_modules/next/dist/server/next-server.js:904:37) {
  name: 'LinkAccountError'
}
```

### Contributing  🙌🏽

Yes, I am

**Comment by kushthakker** [comment]
Having the same issue. Would really appreciate a reply to this problem.

**Comment by kushthakker** [comment]
> Having the same issue. Would really appreciate a reply to this problem.  

Anyone??? 
I am stuck on a project for weeks because I opt in to use next-auth. Would really appreciate help here.

**Comment by joziahg** [comment]
When running into this issue, I changed the id_token field to `@db.Text`

**Comment by kushthakker** [comment]
Tried doing db.Text and db.LongText but still having the same error.

**Comment by dialnco** [comment]
stumbled on the same problem using planet scale as db provider. Checking existing examples on planet scale repos I arrived on this commit that fix this issue on ```schema.prisma```: [https://github.com/exponent42/nextjs-planetscale-starter/commit/fc57e3b1dbccfd5608af92638f9a889d3d3db890](https://github.com/exponent42/nextjs-planetscale-starter/commit/fc57e3b1dbccfd5608af92638f9a889d3d3db890)

The solution is the addition of:
```js
   ...
   refresh_token            String? @db.VarChar(500)
   access_token             String? @db.VarChar(500)
   ...
   id_token                 String? @db.Text
   ...
```

Having the same problem, can confirm this snippet fixed the error.

**Comment by techgerm** [comment]
@dialnco that worked! You're a true lifesaver 🙌

**Comment by kushthakker** [comment]
> stumbled on the same problem using planet scale as db provider. Checking existing examples on planet scale repos I arrived on this commit that fix this issue on ```schema.prisma```: [https://github.com/exponent42/nextjs-planetscale-starter/commit/fc57e3b1dbccfd5608af92638f9a889d3d3db890](https://github.com/exponent42/nextjs-planetscale-starter/commit/fc57e3b1dbccfd5608af92638f9a889d3d3db890)
> 
> 
> 
> The solution is the addition of:
> 
> ```js
> 
>    ...
> 
>    refresh_token            String? @db.VarChar(500)
> 
>    access_token             String? @db.VarChar(500)
> 
>    ...
> 
>    id_token                 String? @db.Text
> 
>    ...
> 
> ```
> 
> 
> 
> Having the same problem, can confirm this snippet fixed the error.

Thank-you very much @dialnco

**Comment by balazsorban44** [comment]
Closing in favor of https://github.com/nextauthjs/docs/pull/178 and https://github.com/nextauthjs/docs/pull/182
