### ISSUE TITLE
Error using MongoDB adapter example.

### ISSUE THREAD

**Issue by callumok2004** [nextauthjs/adapters#293]
### Question 💬

Using the exact code given in the MongoDB adapter guide, I get the following error.
https://next-auth.js.org/adapters/mongodb

![a](https://i.callumdev.xyz/cwvjy.png)

### How to reproduce ☕️

https://github.com/callumok2004/nextjs-reproduction/

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
the problem seems to happen before you actually use mongodb with next-auth. I would recommend looking around how to set up a Mongo client with Next.js.

I simply used the official example from here https://github.com/vercel/next.js/blob/canary/examples/with-mongodb/lib/mongodb.js

**Comment by callumok2004** [comment]
> the problem seems to happen before you actually use mongodb with next-auth. I would recommend looking around how to set up a Mongo client with Next.js.
> 
> I simply used the official example from here https://github.com/vercel/next.js/blob/canary/examples/with-mongodb/lib/mongodb.js

That is the exact example I am using...?? Just without all the comments, added semi-colons etc

**Comment by balazsorban44** [comment]
could you try using it outside of next-auth to confirm if it's actually a problem with next-auth or not? I have  a feeling this is an upstream issue.

**Comment by callumok2004** [comment]
@balazsorban44 the issue in the mentioned issue is not the same as this one...

**Comment by balazsorban44** [comment]
my bad then. I'll transfer it here and reopen. in any case, if you have an adapter related issue, please open it in this repo next time. helps with maintenance
