### ISSUE TITLE
MongoDB Adapter | m.collection is not a function

### ISSUE THREAD

**Issue by callumok2004** [nextauthjs/adapters#296]
### Question 💬

I am attempting to use the MongoDB database adapter, but it is giving me the error mentioned in the title and I cannot seem to figure out why, any ideas?

### How to reproduce ☕️

https://github.com/callumok2004/nextjs-reproduction

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Your reproduction doesn't seem to follow step 2 of the usage docs https://next-auth.js.org/adapters/mongodb#usage

**Comment by callumok2004** [comment]
I actually logged clientPromise just to debug, and it is resolving correctly, I've also just called the file database instead of mongodb

**Comment by balazsorban44** [comment]
It's still wrong though, step 3 shows you that `db` does not expect a function but a Mongo db instance

**Comment by callumok2004** [comment]
I will have another look when I am on my pc in a few hours, where is it receiving a function, where it is meant to be recieving a Db instance?

**Comment by balazsorban44** [comment]
your repro code mixes v3 and v4 syntax BTW, I suggest you give this a read https://next-auth.js.org/getting-started/upgrade-v4

you could avoid extra db calls like in your session callback. user is already available in that context

**Comment by callumok2004** [comment]
Actually, I see what your looking at now, you can ignore the old Db file in /api/database, the new one is located at /lib/database, which is the one being used in nextAuth dB adapter

**Comment by balazsorban44** [comment]
> I will have another look when I am on my pc in a few hours, where is it receiving a function, where it is meant to be recieving a Db instance?

Check the docs link above. usage, step 3.

**Comment by balazsorban44** [comment]
I recommend you align your reproduction with the docs and the migration guide, if you still experience issue then, I'm happy to reopen.

**Comment by callumok2004** [comment]
![image](https://user-images.githubusercontent.com/35779365/140608353-3ef9424d-1528-46db-887d-953d9630ea69.png)

**Comment by callumok2004** [comment]
Unless I am just completely blind, I do not see any issues on my end, even taking into consideration everything you mentioned.

**Comment by balazsorban44** [comment]
please look at the documentation I sent you. `db` must be a DB instance, not a function

https://github.com/nextauthjs/adapters/blob/c42bfd0fc31a3cd6a811958991da3c4674d826f5/packages/mongodb/src/index.ts#L58

**Comment by callumok2004** [comment]
Ok, now I see what you were saying, now I am having this issue.
![image](https://user-images.githubusercontent.com/35779365/140609673-444b4386-bdcc-48cb-b5cd-c51901559487.png)

The repro repo has been updated.

**Comment by callumok2004** [comment]
![image](https://user-images.githubusercontent.com/35779365/140610051-ce284432-3e92-4f44-af65-b7751d5ebdf8.png)

![image](https://user-images.githubusercontent.com/35779365/140610040-3542eacd-8803-4674-a77b-b722cb406df6.png)

**Comment by callumok2004** [comment]
![image](https://user-images.githubusercontent.com/35779365/140610172-f6db7df0-f25c-459c-a3c4-7370855908da.png)
![image](https://user-images.githubusercontent.com/35779365/140610184-6c7c67fa-47f3-47b9-a851-706a0f33dcf2.png)

**Comment by balazsorban44** [comment]
just one again.. 😂 db is not a function!

**Comment by callumok2004** [comment]
> just one again.. 😂 db is not a function!

Actually, according to the types, it wants a function? Must be an issue there. When I just specify instance without the `() =>` this is what I get.
![image](https://user-images.githubusercontent.com/35779365/140610270-81d10c39-e2c1-44cb-a678-f6a18531c06b.png)

**Comment by callumok2004** [comment]
![image](https://user-images.githubusercontent.com/35779365/140610346-eee6e307-9754-4cea-a8b9-7a0746d31566.png)
@balazsorban44

**Comment by balazsorban44** [comment]
since it's a test file, you can look away from not having the promise the same way, but this should give you an idea

https://github.com/nextauthjs/adapters/blob/c42bfd0fc31a3cd6a811958991da3c4674d826f5/packages/mongodb/tests/index.test.ts#L6-L9

I'm not sure what else to say/show.

We run tests with the adapters, (both TS and functional), so this is most likely a user misconfiguration.

**Comment by callumok2004** [comment]
Ok, I finally got it working with this code, so it would seem I was right with having it as a function 😭 
![image](https://user-images.githubusercontent.com/35779365/140610644-f54b53d4-6941-4f54-b71d-d1c780dc32e9.png)

Once it updates the db, I then get this error
```
[next-auth][error][SESSION_ERROR]
https://next-auth.js.org/errors#session_error Cannot read properties of undefined (reading 'getUser') TypeError: Cannot read properties of undefined (reading 'getUser')
    at getSessionAndUser (E:\Developing\Ryft\Website-Main\node_modules\@next-auth\mongodb-adapter\dist\index.js:95:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async acc.<computed> (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\errors.js:92:16)
    at async Object.session (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\routes\session.js:92:28)
    at async NextAuthHandler (E:\Developing\Ryft\Website-Main\node_modules\next-auth\core\index.js:65:16)
    at async NextAuthNextHandler (E:\Developing\Ryft\Website-Main\node_modules\next-auth\next\index.js:40:7)
    at async auth (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:22:12)
    at async Object.apiResolver (E:\Developing\Ryft\Website-Main\node_modules\next\dist\server\api-utils.js:102:9)
    at async DevServer.handleApiRequest (E:\Developing\Ryft\Website-Main\node_modules\next\dist\server\next-server.js:1014:9) {
  name: 'GetSessionAndUserError'
}
```

**Comment by balazsorban44** [comment]
you might be using an old version.? try to verify the ismtalled version in `node_modules`. you can see the test file, and it's working as expected.

This is the newest version published to npm at the moment.:

https://unpkg.com/browse/@next-auth/mongodb-adapter@0.0.2-next.285/dist/index.d.ts

**Comment by callumok2004** [comment]
![image](https://user-images.githubusercontent.com/35779365/140611600-9d3e897e-96be-45d6-8f13-af669b63117d.png)

**Comment by callumok2004** [comment]
It also throws random errors at times such as this
```
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
  message: 'decryption operation failed',
  stack: 'JWEDecryptionFailed: decryption operation failed\n' +
    '    at gcmDecrypt (E:\\Developing\\Ryft\\Website-Main\\node_modules\\jose\\dist\\node\\cjs\\runtime\\decrypt.js:66:15)\n' +
    '    at decrypt (E:\\Developing\\Ryft\\Website-Main\\node_modules\\jose\\dist\\node\\cjs\\runtime\\decrypt.js:91:20)\n' +
    '    at flattenedDecrypt (E:\\Developing\\Ryft\\Website-Main\\node_modules\\jose\\dist\\node\\cjs\\jwe\\flattened\\decrypt.js:119:52)\n' +  
    '    at async compactDecrypt (E:\\Developing\\Ryft\\Website-Main\\node_modules\\jose\\dist\\node\\cjs\\jwe\\compact\\decrypt.js:18:23)\n' + 
    '    at async jwtDecrypt (E:\\Developing\\Ryft\\Website-Main\\node_modules\\jose\\dist\\node\\cjs\\jwt\\decrypt.js:8:23)\n' +
    '    at async Object.decode (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\jwt\\index.js:60:7)\n' +
    '    at async Object.session (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\core\\routes\\session.js:38:28)\n' +
    '    at async NextAuthHandler (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\core\\index.js:65:16)\n' +
    '    at async NextAuthNextHandler (E:\\Developing\\Ryft\\Website-Main\\node_modules\\next-auth\\next\\index.js:40:7)\n' +
    '    at async auth (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:18:12)',
  name: 'JWEDecryptionFailed'
}
```

**Comment by balazsorban44** [comment]
I meant to check the adapter version.

**Comment by callumok2004** [comment]
![image](https://user-images.githubusercontent.com/35779365/140618736-c2eb7a49-efd7-4725-b272-7e4a0ab986bc.png)

**Comment by callumok2004** [comment]
I actually think it's fine now, but I am having another issue with a custom oauth2 provider.
I get the following error.
```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error authorization_endpoint must be configured on the issuer
```

**Comment by callumok2004** [comment]
I think it's fine now but I am having an issue with my custom provider, there doesn't seem to be any way to specify a custom scope?

**Comment by callumok2004** [comment]
I am going to create a new issue as the original issue was solved and it doesn't look like this will be reopened anytime soon.

**Comment by Izhaki** [comment]
I had the very same issue.

The README for `@next-auth/mongodb-adapter` on npmjs.com, which uses the [latest release](https://www.npmjs.com/package/@next-auth/mongodb-adapter/v/0.0.2-pr.193-6071c497.276) says:

```js
db: () => client.db("your-database"),
```

Whereas the [next release tag](https://www.npmjs.com/package/@next-auth/mongodb-adapter/v/0.0.2-next.285) README says (as the [MongoDB guide](https://next-auth.js.org/adapters/mongodb)):

```js
db: (await clientPromise).db("your-database")
```

Hence the confusion.

Solution was to use `"@next-auth/mongodb-adapter": "next"` and use the latter (non-function) API.
