### ISSUE TITLE
MongoDB Adapter: db is not a function

### ISSUE THREAD

**Issue by MZ071999** [nextauthjs/adapters#304]
### Title

NextAuth MongoDB Adapter: db is not a function

### How to reproduce ☕️

n/a

### Your question/bug report 📓

I am following the docs https://next-auth.js.org/adapters/mongodb but I got this error

"TypeError: db is not a function"

my adapter is already version 276 so this #210  doesn't help

[...nextauth].js file:
```
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import { MongoDBAdapter } from "@next-auth/mongodb-adapter";
import clientPromise from "../../../utils/mongodb";

export default async function auth(req, res) {
  return await NextAuth(req, res, {
    providers: [
      GoogleProvider({
        clientId: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      }),
    ],
    adapter: MongoDBAdapter({
      db: (await clientPromise).db("your-database"),
    }),
    callbacks: {
      redirect: async (url, _) => {
        if (url == "/api/auth/signin") {
          return Promise.resolve("/home");
        }
        return Promise.resolve("/home"); 
      },
      session: async (session, user, _sessionToken) => {
        return Promise.resolve(session);
      },
    },
  });
}
```

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
could you check the adapter version in node_modules to be sure?

**Comment by nicholasherious** [comment]
Having the same issue.

**Comment by balazsorban44** [comment]
> could you check the adapter version in node_modules to be sure?

**Comment by michalscislowski** [comment]
I have exactly the same issue for firebase adapter

**Comment by MZ071999** [comment]
I run `npm uninstall` and uninstall all packages then run this command from the docs:

`npm install next-auth@beta @next-auth/mongodb-adapter@next mongodb`

my problem is solved now
