### ISSUE TITLE
Github + Prisma adapter doesn't store refresh token

### ISSUE THREAD

**Issue by AashJ** [nextauthjs/adapters#311]
### Title

Github + Prisma adapter doesn't store refresh token

### How to reproduce ☕️

```
export default NextAuth({
    // Configure one or more authentication providers
    adapter: PrismaAdapter(prisma),
    providers: [
        GitHubProvider({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET,
            authorization: {
                params: {
                    scope: 'read:user user:email repo',
                },
            },
        }),
    ],
```

### Your question/bug report 📓

When using the GitHubProvider + PrismaAdapter, my account table doesn't have the user's refresh token + expiration information

```
export default NextAuth({
    // Configure one or more authentication providers
    adapter: PrismaAdapter(prisma),
    providers: [
        GitHubProvider({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET,
            authorization: {
                params: {
                    scope: 'read:user user:email repo',
                },
            },
        }),
    ],
```

A row in the account table looks something like (with information redacted):

```
{
  id: '------------------------------',
  userId: '-----------------------------',
  type: 'oauth',
  provider: 'github',
  providerAccountId: '-------------------',
  refresh_token: null,
  access_token: '------------------------------',
  expires_at: null,
  token_type: 'bearer',
  scope: 'read:user,repo,user:email',
  id_token: null,
  session_state: null,
  oauth_token_secret: null,
  oauth_token: null
}
```

The refresh token is null preventing me from doing a refresh token rotation.

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
If it is not there, then GitHub does not return it to you for some reason. We don't strip any fields sent by your provider.

Check out the note on top of this page as well: https://next-auth.js.org/providers/github

**Comment by AashJ** [comment]
My apologies, seems like github oauth tokens don't expire until permission is revoked, so no need for a refresh token:

https://stackoverflow.com/questions/26902600/whats-the-lifetime-of-github-oauth-api-access-token
