### ISSUE TITLE
Module parse failed: The top-level-await experiment is not enabled

### ISSUE THREAD

**Issue by Izhaki** [nextauthjs/adapters#312]
### Title

Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)

### How to reproduce ☕️

1. Follow the README instructions here: https://github.com/nextauthjs/next-auth-example/tree/ndom91/update-v4
2. Follow the MongoDB guide: https://next-auth.js.org/adapters/mongodb
3. Run `npm run start`

There is no need to configure a mongo instance to see the issue - the build breaks before we even get to access mongo.

Packages versions:
```
    "next-auth": "4.0.0-beta.7",
    "@next-auth/mongodb-adapter": "next",
```

Where `next` resolves to `0.0.2-next.285`.

### Your question/bug report 📓

With this setup, due to this line:

```js
db: (await clientPromise).db("your-database")
```

the build breaks with:

```shell
error - ./pages/api/auth/[...nextauth].js
Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
Error: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
(node:89742) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
```

# Solution 1

To solve this one needs in `next.config.js`:

```js
module.exports = {
  webpack: (config) => {
    config.experiments.topLevelAwait = true;
    return config;
  },
};
```

# Solution 2

The API has recently changed from a function to a variable (as mentioned in [this issue](https://github.com/nextauthjs/adapters/issues/296#issuecomment-973616331))

Maybe revert back to a function?

### Contributing  🙌🏽

Yes, I am

**Comment by balazsorban44** [comment]
https://next-auth.js.org/adapters/mongodb

**Comment by Izhaki** [comment]
Not sure why this was closed.

As I mentioned, I was following 

> Follow the MongoDB guide: https://next-auth.js.org/adapters/mongodb

And it is exactly this approach that breaks the build.

**Comment by balazsorban44** [comment]
if you followed it, this error message wouldn't show up. you are calling something in the wrong place.

could you share a reproduction?

**Comment by Izhaki** [comment]
https://github.com/Izhaki/next-auth-example/tree/issue-312

With the only changes on top of https://github.com/nextauthjs/next-auth-example/tree/ndom91/update-v4 here: https://github.com/Izhaki/next-auth-example/commit/5a33ffc5a949504522f549ce64c6a91242b59f34

> There isn't any top-level await in the docs

Definitely doesn't look like it, but for some reason webpack breaks the build. Maybe an issue with `next-swc-loader`?

**Comment by balazsorban44** [comment]
checked your repro, you aren't following the docs correctly, have another look.

**Comment by Izhaki** [comment]
Any pointers?

**Comment by balazsorban44** [comment]
https://github.com/Izhaki/next-auth-example/blob/5a33ffc5a949504522f549ce64c6a91242b59f34/pages/api/auth/%5B...nextauth%5D.js#L15

https://github.com/nextauthjs/docs/blob/cd693562d23ad0151bca16089585ffc1e77c52a2/docs/adapters/mongodb.md?plain=1#L67

**Comment by Izhaki** [comment]
Jesus! Thanks for that!
