### ISSUE TITLE
Add support for Prisma Data Proxy

### ISSUE THREAD

**Issue by milovangudelj** [nextauthjs/adapters#318]
### Title

Add support for Prisma Data Proxy

### How to reproduce ☕️

Create a new Next.js application using `create-next-app`.

Install the necessary dependencies to be able to use Prisma in the project like shown in this [official guide](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases-typescript-postgres).
I'm using PostgreSQL, but it doesn't really matter which database you chose.

Follow the instructions in this other [official guide](https://www.prisma.io/docs/concepts/components/prisma-data-platform#using-the-data-proxy-in-a-prisma-application) to set up the data proxy in the newly created project.

Then set up next-auth to be used with the Prisma adapter as shown in the [official adapter guide](https://next-auth.js.org/adapters/prisma).

If it's necessary I'll create a codesandbox with everything already set up.

### Your question/bug report 📓

In my case I was using the Email provider together with SendGrid, and after running `yarn dev` the application compiles successfully but an error pops up in the console saying ```Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.```

I assume the problem is caused by the fact that I'm using a data proxy URL that starts with `prisma://` instead of the regular one.

I understand that this is a new feature (Prisma released it just a few days ago, and it's still in early access) so this is not really a bug or issue but more of a feature request.

I'm not a seasoned dev so a PR is not an option 😅

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by williamluke4** [comment]
Hey
Have you set this env var `PRISMA_CLIENT_ENGINE_TYPE='dataproxy`  https://www.prisma.io/docs/concepts/components/prisma-data-platform#step-5-generate-the-client

**Comment by balazsorban44** [comment]
Sounds like this isn't an issue on our side. Please come back if the above suggestion did not help.
