### ISSUE TITLE
Stabilize TypeORM CI Tests

### ISSUE THREAD

**Issue by williamluke4** [nextauthjs/adapters#32]
https://github.com/nextauthjs/adapters/runs/1856600210#step:5:43

**Comment by balazsorban44** [comment]
I just had a look at it, and it does seem to time out, but only sometimes.

**Comment by balazsorban44** [comment]
I think something like the Prisma tests would be ideal.

We could add integration tests as well, but I'm still waiting on feedback from @iaincollins on how he thinks it should be done correctly.

**Comment by balazsorban44** [comment]
See #90
