### ISSUE TITLE
Make it possible to use prefix for collections

### ISSUE THREAD

**Issue by 4nduril** [nextauthjs/adapters#321]
### Title

Make it possible to use prefix for collections like entityPrefix in TypeORM

### How to reproduce ☕️

I don't think it's useful to provide code to reproduce a feature request here.

### Your question/bug report 📓

With next-auth v3 I used the typeORM adapter with MongoDB as shown in the docs. There was also a hint (https://next-auth.js.org/v3/configuration/databases#how-to-use-a-database) how you could use `entityPrefix` to have all "tables" aka collections that the adapter is going to create get a prefixed name.

Today I switched to v4 and adapters@next and as per documentation I used the separate adapter for MongoDB. But this one is lacking the option for collection name prefixing. 

My suggestion would be an additional config option besides `db` which would be optional and called `collectionPrefix`. 

I had a quick look on the code of the adapter and it's so straight forward that I would implement it and open a PR against the next branch if that's fine? Any thoughts?

### Contributing  🙌🏽

Yes, I am

**Comment by balazsorban44** [comment]
Already possible?

![image](https://user-images.githubusercontent.com/18369201/143484076-7ade9855-4f26-4864-8aba-919fef40586f.png)

**Comment by balazsorban44** [comment]
Wait a sec, it's MongoDB, I see now...

**Comment by balazsorban44** [comment]
Yeah, I think we are fine with a PR. 

Would it be enough to expose collections as an option?

https://github.com/nextauthjs/adapters/blob/e6915fa1dcba9b12f26bed55cddcb3b3bcd7b07c/packages/mongodb/src/index.ts#L58-L69

**Comment by 4nduril** [comment]
I have opened a PR with my initial thoughts of a prefix option that works like the one in TypeORM. If you think we should allow to give the collection names completely as an option, I can do that instead.

**Comment by balazsorban44** [comment]
I think that would be more flexible, yes.

**Comment by balazsorban44** [comment]
Fixed in  #323
