### ISSUE TITLE
Requirements for new adapter

### ISSUE THREAD

**Issue by kay-is** [nextauthjs/adapters#338]
I am tasked with writing a new adapter and wanted to ask what I should keep in mind before starting.

The database is Upstash Redis, a hosted service, and I run tests with the free plan. Is this okay for you? Upstash will supply API credentials for your CI pipeline later.

Thanks!

**Comment by balazsorban44** [comment]
https://next-auth.js.org/adapters/overview
https://next-auth.js.org/adapters/models
https://next-auth.js.org/tutorials/creating-a-database-adapter

**Comment by kay-is** [comment]
@balazsorban44 Thanks for the links!

It would be cool if someone who knows how things work in the background could write a paragraph or two for each adapter method [here](https://next-auth.js.org/tutorials/creating-a-database-adapter). Like what it does, how it's called by Next.js later, etc.

**Comment by balazsorban44** [comment]
It isn't called by Next.js.

Most of them are very explanatory IMO, but here is the type definition as well, if helps

https://github.com/nextauthjs/next-auth/blob/main/src/adapters.ts

you can check https://github.com/nextauthjs/adapters/tree/main/packages for  examples.

I'm happy to accept a PR to the docs though.
