### ISSUE TITLE
adapter_error_getUserByAccount Fauna DB

### ISSUE THREAD

**Issue by axk2** [nextauthjs/adapters#342]
### Title

[next-auth][error][adapter_error_getUserByAccount]

### How to reproduce ☕️

[...nextauth].tsx file

```tsx
import NextAuth from "next-auth"
import GitHub from "next-auth/providers/github"
import Twitter from "next-auth/providers/twitter"
import { Client as FaunaClient } from "faunadb"
import { FaunaAdapter } from "@next-auth/fauna-adapter"


const client = new FaunaClient({
    secret: process.env.FAUNA_SECRET,
    scheme: "https",
    domain: "https://db.us.fauna.com",
    port: 8443,
})


export default NextAuth({
    providers: [
        GitHub({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET,
        }),
        Twitter({
            clientId: process.env.TWITTER_ID,
            clientSecret: process.env.TWITTER_SECRET,
        })
    ],
    adapter: FaunaAdapter(client),
    secret: process.env.SECRET,
    session: {
        strategy: 'jwt'
    },
    jwt: {
        secret: process.env.SECRET,
    },
})
```

faunadb: "^4.4.1",
@next-auth/fauna-adapter: "^1.0.1",
next-auth: "^4.0.5",

i am just starting with next auth, so i only have a page with a button with a signIn() function

when you click it and try to login will appear 2 buttons (github and twitter), and when you login, the callback to http://localhost:3000/api/auth/callback/github will throw an error in the console

the error is very long
```sh
[next-auth][error][adapter_error_getUserByAccount]
https://next-auth.js.org/errors#adapter_error_getuserbyaccount The pending stream has been canceled (caused by: getaddrinfo ENOTFOUND https) {
  message: 'The pending stream has been canceled (caused by: getaddrinfo ENOTFOUND https)',
  stack: 'Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: getaddrinfo ENOTFOUND https)\n' +
    '    at new NodeError (node:internal/errors:329:5)\n' +
    '    at closeSession (node:internal/http2/core:1095:20)\n' +
    '    at ClientHttp2Session.destroy (node:internal/http2/core:1472:5)\n' +
    '    at Socket.socketOnError (node:internal/http2/core:2922:13)\n' +
    '    at Socket.emit (node:events:369:20)\n' +
    '    at Socket.emit (node:domain:470:12)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:188:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:153:3)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:81:21)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error The pending stream has been canceled (caused by: getaddrinfo ENOTFOUND https) Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: getaddrinfo ENOTFOUND https)
    at new NodeError (node:internal/errors:329:5)
    at closeSession (node:internal/http2/core:1095:20)
    at ClientHttp2Session.destroy (node:internal/http2/core:1472:5)
    at Socket.socketOnError (node:internal/http2/core:2922:13)
    at Socket.emit (node:events:369:20)
    at Socket.emit (node:domain:470:12)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  name: 'GetUserByAccountError',
  code: 'ERR_HTTP2_STREAM_CANCEL'
}
```
i've tried changing the new FaunaClient() information but it didn't worked

if i remove the adapter everything works fine, but i would love use the faunadb adapter to have specific user information because i want to create a multi tenant system...

i've created index and collections like the documentation says: https://next-auth.js.org/adapters/fauna
i've tried diferents ports and domains, i am from south america and use domain: "https://db.us.fauna.com"

### Your question/bug report 📓

https://next-auth.js.org/errors#adapter_error_getuserbyaccount

this url error is not even in the documentation... the faunadb adapter is not working, i've made this steps https://next-auth.js.org/adapters/fauna

but i can't login

without the adapter i can login perfectly, but it would be great to use it.

these are the versions, i don't know if there is a stable one and i should change
faunadb: "^4.4.1",
@next-auth/fauna-adapter: "^1.0.1",
next-auth: "^4.0.5",

if there is a way i could help let me know

thanks

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
I cannot reproduce. could you link to a reproduction?

at first glance, it doesn't seem to be next-auth related.

**Comment by axk2** [comment]
my bad, a very noob error, i put https:// in the domain. that's it.
everything working like a charm.
a very nice job and a very nice library.
thanks
