### ISSUE TITLE
Server Error TypeError: Cannot read property 'apps' of undefined

### ISSUE THREAD

**Issue by viperfx** [nextauthjs/adapters#359]
### Description 🐜

When following the firebase adapter docs, I get the following error

Since I don't use the firebase DB at all - I removed that.

```
import firebase from "firebase/app";

const firestore =
  firebase.apps[0] ??
  firebase.initializeApp({
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: `${process.env.FIREBASE_PROJECT_ID}.firebaseapp.com`,
    projectId: process.env.FIREBASE_PROJECT_ID,
  });

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export default NextAuth({
  adapter: FirebaseAdapter(firestore),
```

### Is this a bug in your own project?

No

### How to reproduce ☕️

- Clone next-auth example project
- Setup firebase project

### Screenshots / Logs 📽

<img width="1023" alt="CleanShot 2021-12-30 at 15 19 33@2x" src="https://user-images.githubusercontent.com/328257/147791570-a55a01ca-2196-420e-8816-519e457e0d66.png">

### Environment 🖥

```
  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 227.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.0
  npmPackages:
    next: ^12.0.7 => 12.0.7 
    next-auth: latest => 4.0.6 
    react: ^17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
For the record, the firebase adapter is currently not compatible with the `latest` version of `next-auth` and hasn't been properly tested yet. I apologize for the confusion. I now added a note to the docs. See #183 for more info. Although, the original issue doesn't even seem to be `next-auth` specific.
