### ISSUE TITLE
Actually splitting the adapters out of `next-auth`

### ISSUE THREAD

**Issue by ndom91** [nextauthjs/adapters#37]
Hey guys so I'm trying to begin testing ripping out the adapters from the main repo and I'm having trouble with the docker setup / linking my local copy of the adapters repo.

So here's my current setup:
/opt/ndom91/adapters = `nextauthjs/adapters` repo
/opt/ndom91/next-auth = `nextauthjs/next-auth` repo

`npm link`-ed (1) to (2) under `@next-auth/typeorm-adapter` so that symlinked `/opt/ndom91/next-auth/node_modules/@next-auth/typeorm-adapter` to my local copy of the adapter at `/opt/ndom91/adapters/packages/typeorm`. Problem is that is not available in the docker container that's spun up for the integration portion of the tests in next-auth because it just uses `/opt/ndom91/next-auth/tests/..` as the base for the container.

Any idea or tips on the best way to go about this? I tried to manually copy the required files into the right location in the Dockerfile in next-auth but that's not a real solution cause you'd need to define paths manually every time. So the only thing I can really think of is possibly running the next-auth integration tests not inside a docker container. What do you guys think?

Now that next-auth tests themselves wouldn't be spinning up any databases, I think we can drop all the docker testing related stuff in the next-auth repo itself. All that would then only belong in the adapters repo to test the specific adapter backends. next-auth itself can be tested like any other react app/library by spinning up a node server with the test app we have in the testing subdirectory. Or am I missing something?

CC: @iaincollins

**Comment by n44ps** [comment]
Hey, what's the ETA of this config ? I would love to help for the Fauna Adapter :)

**Comment by balazsorban44** [comment]
No ETA. :) You can have a look at the code in https://github.com/nextauthjs/adapters/pull/5 so you could simply use the src code until it has been released here.

**Comment by n44ps** [comment]
Yeah, I meant the release :p I was helping for the first PR in the nextauth repo ^^ I'm eager to see it on a proper npm package !

**Comment by balazsorban44** [comment]
cc @pbteja1998 whenever you have a second, could you look at this? As mentioned in our Twitter discussion, you only need to push a commit, so the release flow wouldn't fail, and a new release could be pushed to npm.

**Comment by pbteja1998** [comment]
@balazsorban44 I just removed typescript and just added the javascript file. I think we can improve it later to use TypeScript and also give a way to setup the schema and migrations like you have with `prisma`. Please let me know if anything else needs to be done to get this released to npm package.

**Comment by balazsorban44** [comment]
I created #63 to address the current Prisma Adapter migration. It is marked as legacy, and we will only keep it around until we released `4.0`.

The next steps:

- `@next-auth/prisma-legacy-adapter` and `@next-auth/typeorm-legacy-adapter` should be added as dependencies to `next-auth`
- Any adapter code should be removed from the main repo
- In the https://github.com/nextauthjs/next-auth/tree/main/src/adapters, simply re-export the necessary things from the new (but legacy :upside_down_face:) adapters

**Comment by balazsorban44** [comment]
All the steps on this list is done! The adapters have been migrated from the source code! :tada:

**Comment by balazsorban44** [comment]
Arguably the TypeORM tests should be improved, but it is followed here #32

**Comment by ndom91** [comment]
Just caught up with all this work. Great job @balazsorban44 :tada: :tada:
