### ISSUE TITLE
uuid or cuid for Prisma adaptor model IDs

### ISSUE THREAD

**Issue by jasonkuhrt** [nextauthjs/adapters#38]
I would like to use `cuid` for model IDs in our Prisma schema.

This will require changing the type of the field.

This in turn forces some of the TS types to change, e.g. `linkAccount` function `userId` paramter changes from `number` to `string`.

Would it be acceptable for force Next Auth Prisma adaptor users to use `String` type for model IDs?

Or is there an easy way to support both `Int` based IDs and `String` based model IDs?

**Comment by jasonkuhrt** [comment]
It seems all that is needed is to do this in the implementation to keep it type safe:

```ts
type UserId = Prisma.User['id']

// replace hard-coded `number` with references to `UserId`
```

**Comment by kripod** [comment]
I just noticed in the [Prisma adapter’s code](https://github.com/nextauthjs/adapters/blob/canary/packages/prisma/src/index.ts) that `number` and `string` aren’t used consistently for `userId`. It seems there shouldn’t be any difference in runtime, but I think those types should be changed as written above.
