### ISSUE TITLE
Can't find mentioning of `useUnifiedTopology` and `useNewUrlParser` in node mongodb docs

### ISSUE THREAD

**Issue by DiamondeX** [nextauthjs/adapters#381]
### Title

Can't find mentioning of `useUnifiedTopology` and `useNewUrlParser` in node mongodb docs

### How to reproduce ☕️

1. Open https://github.com/nextauthjs/adapters/blob/main/packages/mongodb/README.md
2. Look at "Getting Started" section, step 2.
You should find this code there:
```ts
const options = {
  useUnifiedTopology: true,
  useNewUrlParser: true,
}
```

### Your question/bug report 📓

I have tried to find an explanation about `useUnifiedTopology` and `useNewUrlParser` options in the documentation of "MongoDB NodeJS Driver" (The official [MongoDB](https://www.mongodb.com/) driver for Node.js), but didn't find anything.
Probably those options were long removed. Isn't it the case?

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by DiamondeX** [comment]
Btw, using this code with typescript gives this error:
`Type '{ useUnifiedTopology: boolean; useNewUrlParser: boolean; }' has no properties in common with type 'MongoClientOptions'.ts(2559)`

**Comment by balazsorban44** [comment]
https://next-auth.js.org/adapters/mongodb

**Comment by DiamondeX** [comment]
@balazsorban44 The link you have provided does confirm, that this kind of code is used in nextauth official docs, and not only in readme inside its git-repo, but you said nothing about if those options are really needed. Moreover, as I've mentioned, this code is not working in typescript, because those options are absent in `MongoClientOptions` interface. So I would consider the example code on the page you linked to to be misleading. If there is another place, where I have to report this issue, then I would appreciate, if you tell me about it.
