### ISSUE TITLE
Create stable release of all the adapters

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/adapters#68]

**Comment by ndom91** [comment]
Just wanted to drop a comment here for us not to forget to clean up the `typeorm-legacy` / `prisma-legacy` naming stuff.

Maybe drop the two 'legacy' versions and just roll with the "new" `typeorm` and `prisma` implementations once this is ready :+1:

**Comment by balazsorban44** [comment]
yes, we could try that. I'm even hoping that maybe we could have one unified Prisma adapter, it feels overcomplicated to maintain two almost identical versions.

cc @kripod

**Comment by ndom91** [comment]
Yeah that's what I'm trying to get at - just simplify this whole typeorm/prisma two version thing

**Comment by kripod** [comment]
@balazsorban44 the legacy adapter uses a different schema with worse indexing capabilities, so it isn’t compatible with the new version at all.

**Comment by ndom91** [comment]
@kripod so there would be no easy way to migrate users? Even if we supplied a schema migration script?

Maybe we have to keep around the `prisma-legacy` adapter for a while then and keep recommending people move to / only use the "new" version and then after a few months  / major versions slowly deprecate it. What do you guys think?

**Comment by kripod** [comment]
@ndom91 Migration is absolutely possible. At least, we did it without severe outage at [Copyfolio](https://copyfol.io/). Providing a codemod is a great idea and I totally support keeping only the more recent version of the adapter.

**Comment by balazsorban44** [comment]
To be able to get rid of the old one, the new one still has to support all the old features (meaning option to change table names) so we don't break anything. People seem to be interested in this as a feature, and if we decide to move forward with it for other adapters, it only makes sense if we do the same with `prisma` as well.

**Comment by kripod** [comment]
We can’t support older schema versions with the new adapter, as the required multi-column unique constraints aren’t there to be used, and thus, queries referencing those constraints would fail, see:

https://github.com/nextauthjs/adapters/blob/ebd8245aa087cb495bd20c61014abc58c1327131/packages/prisma/src/index.ts#L50-L55

https://github.com/nextauthjs/adapters/blob/ebd8245aa087cb495bd20c61014abc58c1327131/packages/prisma/src/index.ts#L99-L105

https://github.com/nextauthjs/adapters/blob/ebd8245aa087cb495bd20c61014abc58c1327131/packages/prisma/src/index.ts#L168-L187

**Comment by ndom91** [comment]
Yeah if it can be done with a short tutorial / codemod / script or something along those lines, I'm all for it too. 

Maybe we should start telegraphing that the "legacy" versions of the adapters are not to be used with green field projects and were getting ready to deprecate them and will provide migration help. Obviously more of a medium to long term thing, but I think it'd be useful to let people know already. 

Maybe a line or two in the readmes and a tweet or something like that?

**Comment by balazsorban44** [comment]
would we want to make a new typeorm adapter as well? or that one is safe to stay, just drop the legacy from the name?

**Comment by ndom91** [comment]
Whats the difference between `typeorm` and `typeorm-legacy`? Or technically there is no `typeorm`, right? Its only `typeorm-legacy`?

Then yeah whenever we decide to rip out the typeorm stuff from the core package, i would also remove the 'legacy' label from it here :+1:

**Comment by balazsorban44** [comment]
No difference. We only have 2 prisma adapters also, because the work on a new version has started in community space, instead of upgrading the existing one. And as I understand, it wouldn't have been possible anyway, because there are breaking changes.

I plan to remove the adapters from the core in v4. (Releasing it this summer would be my goal for now. :crossed_fingers:)

**Comment by ndom91** [comment]
Okay great, sounds good! Then with v4 we can maybe also consolidate this prisma + typeorm "legacy" situation and simplify things for ourselves and our users :+1:

**Comment by balazsorban44** [comment]
So we get a lot of issues regarding problems that have already been resolved on canary.

The reason is that in our code examples, we recommend installing like this:

`npm install @next-auth/foo-adapter`.

The problem with this is that it tries to install `latest` by default, which without getting the adapters to `main` are usually very outdated versions. We should either accelerate the process of this issue, or change our documentation to rather recommend:

`npm install @next-auth/foo-adapter@canary` instead.

**Comment by ndom91** [comment]
Yeah good call - I'm down for either. What do you think? 

Are they stable enough to release a new latest of them all?

**Comment by ndom91** [comment]
Update: docs have all been updated to recommend installing `@canary` releases for now :+1:

**Comment by ndom91** [comment]
We've created `1.0.0` releases of all stable adapters, as well as created tags for said releases on Github.
