### ISSUE TITLE
[prisma] use a faster LRU implementation, e.g. `mnemonist-object`

### ISSUE THREAD

**Issue by kripod** [nextauthjs/adapters#69]
According to the [bench-lru](https://github.com/dominictarr/bench-lru) repository and [this article](https://yomguithereal.github.io/posts/lru-cache), there are LRU implementations which perform way better than `lru-cache`, which is in use right now. I would suggest using `mnemonist/lru-cache` as a replacement for it, based on the benchmarks.

**Comment by balazsorban44** [comment]
Closing in favor of #70
