### ISSUE TITLE
Add Firebase 🔥 adapter

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/adapters#84]
By the [permission given](https://github.com/nextauthjs/next-auth/discussions/723#discussioncomment-324826) from @RonHouben, I challenge someone from the community to add a new firebase adapter to our 

https://github.com/nextauthjs/adapters repository, with the name `@next-auth/firebase-adapter`.

You can use the following source code, where most of the work has already been done (thanks @RonHouben!): https://github.com/RonHouben/nextjs-tailwindcss-todo-app/blob/c55af99329f5206d31eec8f87405873e111895c6/lib/firebaseAdapter.ts

If anyone will take this, I am going to try to help to get this merged according to the best of my abilities!

**Comment by ndom91** [comment]
@RonHouben we've released the firebase adapter in the canary branch!

**Comment by balazsorban44** [comment]
UPDATE: The GitHub Action is being stubborn, so the canary release is not published, but here is how you could try it out:

`npm i @next-auth/firebase-adapter@0.0.2-pr.18.173`

**Comment by Kashishjain04** [comment]
Can you please provide appropriate documentation for FirebaseAdapter like how can i mention my collections to store users data

**Comment by balazsorban44** [comment]
You shouldn't be needing it, it defaults to the collections:

`users`, `sessions`, `accounts` and `verificationRequests`.

**Comment by balazsorban44** [comment]
we will consider if we should make these names overrideable.

**Comment by Kashishjain04** [comment]
Ok, I found it Thanks a lot 👍🏻
