### ISSUE TITLE
canary-127 legacy-prisma adapter is completely broken, now in production package

### ISSUE THREAD

**Issue by zackdotcomputer** [nextauthjs/adapters#93]
I just upgraded to 3.23 of next-auth and I'm now getting this error when my endpoint it hit:
```
TypeError: next_auth_adapters__WEBPACK_IMPORTED_MODULE_2___default(...).Prisma.Adapter is not a function
    at eval (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:51:77)
    at Module../src/pages/api/auth/[...nextauth].ts (/Users/zack/code/traveler/tweetsweep/app/.next/server/pages/api/auth/[...nextauth].js:88:1)
    at __webpack_require__ (/Users/zack/code/traveler/tweetsweep/app/.next/server/webpack-runtime.js:33:43)
    at __webpack_exec__ (/Users/zack/code/traveler/tweetsweep/app/.next/server/pages/api/auth/[...nextauth].js:175:52)
...
```

Any ideas off the bat what might be causing this? No code was changed.

**Comment by zackdotcomputer** [comment]
It looks like it was between canary-115 and canary-127 - digging deeper.

**Comment by zackdotcomputer** [comment]
`console.debug(Adapters.Prisma)` prints out `{ Adapter: [Getter] }`

`console.debug(Adapters.Prisma.Adapter)` prints out `undefined`

This appears to just be broken? Not great.

**Comment by zackdotcomputer** [comment]
@balazsorban44 do you have more guidance on how to get around this?

**Comment by balazsorban44** [comment]
Please stop opening duplicate issues for the same problem, it doesn't accelerate your case... It only creates maintenance overhead. Also, tagging maintainers for no real reason is the same. I understand it might be frustrating, and I will obviously look into it, but I don't have the capacity to  answer everyone who tags me. Please see the other issue you opened, and ignore this one.

**Comment by zackdotcomputer** [comment]
If you, future developer, come across this issue, go check out [this other issue](https://github.com/nextauthjs/next-auth/issues/2008) where, as requested, I'll collect what I find out.
